'use client';
import styles from './page.module.css';
import React, { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  Database, PlusCircle, Search, Edit3, Trash2, Eye, Filter, ArrowDownToLine, ArrowLeft
} from 'lucide-react';
import { useToast } from '@/components/builder/ToastProvider';
import { RouteGuard, useApiClient } from '@unerp/framework';

interface BuilderModule {
  id: string;
  slug?: string;
  entities?: unknown;
  name?: string;
  description?: string;
}

interface SchemaRegistry {
  id: string;
}

interface CustomRecord {
  id: string;
  data: Record<string, unknown>;
  createdAt: string;
}

export default function CustomModulePage() {
  const client = useApiClient();
  const params = useParams();
  const router = useRouter();
  const { showToast } = useToast();

  const [moduleData, setModuleData] = useState<BuilderModule | null>(null);
  const [schemaId, setSchemaId] = useState<string | null>(null);
  const [fields, setFields] = useState<Array<{ name: string; label: string; type: string }>>([]);
  const [records, setRecords] = useState<CustomRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    async function loadCustomApp() {
      setLoading(true);
      try {
        // 1. Fetch all modules and find by slug
        const allModules = await client.get<BuilderModule[]>('/builder/modules');
        const foundModule = allModules.find((m) => m.slug === params.moduleSlug);

        if (!foundModule) {
          showToast('Custom module not found', 'error');
          setLoading(false);
          return;
        }

        setModuleData(foundModule);
        
        const entities = typeof foundModule.entities === 'string' 
          ? JSON.parse(foundModule.entities) 
          : foundModule.entities;
        
        const schemaFields = (entities && entities.length > 0) ? entities[0].fields || [] : [];
        setFields(schemaFields);

        const schema = await client.get<SchemaRegistry>(`/builder/schema-registries/${foundModule.slug}`);
        setSchemaId(schema.id);
        const recordResult = await client.get<{ data?: CustomRecord[] }>(`/builder/custom-records/${schema.id}`);
        setRecords(recordResult.data ?? []);

      } catch (err) {
        showToast('Failed to load custom app', 'error');
      } finally {
        setLoading(false);
      }
    }
    loadCustomApp();
  }, [params.moduleSlug, showToast, client]);

  const handleDelete = async (id: string) => {
    if (!confirm('Delete this record?')) return;
    if (!schemaId) return;
    try {
      await client.delete(`/builder/custom-records/${schemaId}/${id}`);
      setRecords((current) => current.filter((record) => record.id !== id));
      showToast('Record deleted', 'success');
    } catch {
      showToast('Failed to delete record', 'error');
    }
  };

  const createMockRecord = async () => {
    if (!schemaId) {
      showToast('This module does not have a published data schema yet', 'error');
      return;
    }
    const newRecord: Record<string, unknown> = {};
    fields.forEach((f) => {
      if (f.type === 'text') newRecord[f.name] = 'Sample Text';
      if (f.type === 'number') newRecord[f.name] = Math.floor(Math.random() * 100);
      if (f.type === 'date') newRecord[f.name] = new Date().toISOString().split('T')[0];
      if (f.type === 'boolean') newRecord[f.name] = true;
    });
    try {
      const created = await client.post<CustomRecord>(`/builder/custom-records/${schemaId}`, newRecord);
      setRecords((current) => [created, ...current]);
      showToast('Record created', 'success');
    } catch {
      showToast('Failed to create record', 'error');
    }
  };

  if (loading) {
    return <div className="p-6">Loading Custom App...</div>;
  }

  if (!moduleData) {
    return (
      <div className={styles.s1}>
        <h2>Module Not Found</h2>
        <button className="ui-btn" onClick={() => router.push('/builder/erp/modules')}>Return to Builder</button>
      </div>
    );
  }

  const filteredRecords = records.filter(r => 
    Object.values(r.data).some(val =>
      String(val).toLowerCase().includes(searchQuery.toLowerCase())
    )
  );

  return (
    <RouteGuard permission="custom.read">
    <div className="p-6 ui-stack-5">
      {/* Header */}
      <div className="builder-header ui-flex-between ui-items-start">
        <div>
          <div className={styles.s2}>
            <Database size={20} className={styles.s3} />
            <h1 className={styles.s4}>
              {moduleData.name}
            </h1>
          </div>
          <p className={styles.s5}>
            {moduleData.description || `Custom application generated by UniERP Zero-Code Builder`}
          </p>
        </div>
        <div className="ui-flex ui-gap-2">
          <button className="ui-btn ui-btn-primary" onClick={createMockRecord}>
            <PlusCircle size={15} />
            <span>New {moduleData.name}</span>
          </button>
        </div>
      </div>

      <div className={`ui-card ${styles.s6}`} >
        
        {/* Filters bar */}
        <div className="ui-flex-between">
          <div className={styles.s7}>
            <Search size={15} className={styles.s8} />
            <input 
              className={`ui-input ${styles.s9}`} 
              type="text" 
              placeholder={`Search ${records.length} records...`} 
              value={searchQuery} 
              onChange={e => setSearchQuery(e.target.value)} 
               
            />
          </div>
          <div className="ui-flex ui-gap-2">
            <button className="ui-btn ui-btn-secondary"><Filter size={15}/> Filter</button>
            <button className="ui-btn ui-btn-secondary"><ArrowDownToLine size={15}/> Export</button>
          </div>
        </div>

        {/* Data Table */}
        <div className="builder-table-wrapper">
          <table className={`ui-table ${styles.s10}`} >
            <thead>
              <tr>
                <th className={styles.s11}><input type="checkbox" /></th>
                {fields.slice(0, 5).map((f: any) => (
                  <th key={f.name}>{f.label}</th>
                ))}
                <th>Created</th>
                <th className={styles.s12}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredRecords.length === 0 ? (
                <tr>
                  <td colSpan={fields.slice(0, 5).length + 3} className={styles.s13}>
                    No records found. Click 'New' to create one.
                  </td>
                </tr>
              ) : (
                filteredRecords.map((record) => (
                  <tr key={record.id}>
                    <td><input type="checkbox" /></td>
                    {fields.slice(0, 5).map((f: any) => (
                      <td key={f.name}>
                        {f.type === 'boolean' 
                          ? (record.data[f.name] ? 'Yes' : 'No')
                          : String(record.data[f.name] ?? '')}
                      </td>
                    ))}
                    <td className={styles.s14}>{new Date(record.createdAt).toLocaleDateString()}</td>
                    <td className="text-right">
                      <div className={styles.s15}>
                        <button className={`ui-btn ui-btn-secondary ${styles.s16}`} ><Edit3 size={13}/></button>
                        <button className={`ui-btn ui-btn-secondary ${styles.s17}`}  onClick={() => handleDelete(record.id)}><Trash2 size={13}/></button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    </RouteGuard>
  );
}
