/**
 * Worldwide reference lookups for onboarding/registration dropdowns
 * (country, currency, timezone, language, business type, industry).
 *
 * These are display lists only — the API does not enforce membership in
 * these sets (registerSchema keeps them as free-form optional strings), so
 * adding/removing an entry here never requires a backend or migration
 * change.
 */

/** ISO 3166-1 alpha-2 country codes + English short names. */
export const COUNTRIES: Array<{ code: string; name: string }> = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (DRC)" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "Korea (North)" },
  { code: "KR", name: "Korea (South)" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
].sort((a, b) => a.name.localeCompare(b.name));

/** ISO 4217 currency codes in active use, with symbol where commonly rendered. */
export const CURRENCIES: Array<{ code: string; name: string; symbol: string }> =
  [
    { code: "USD", name: "US Dollar", symbol: "$" },
    { code: "EUR", name: "Euro", symbol: "€" },
    { code: "GBP", name: "British Pound", symbol: "£" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥" },
    { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
    { code: "CAD", name: "Canadian Dollar", symbol: "$" },
    { code: "AUD", name: "Australian Dollar", symbol: "$" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "$" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "$" },
    { code: "SGD", name: "Singapore Dollar", symbol: "$" },
    { code: "INR", name: "Indian Rupee", symbol: "₹" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨" },
    { code: "NPR", name: "Nepalese Rupee", symbol: "₨" },
    { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
    { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
    { code: "QAR", name: "Qatari Riyal", symbol: "﷼" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
    { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
    { code: "OMR", name: "Omani Rial", symbol: "﷼" },
    { code: "ILS", name: "Israeli New Shekel", symbol: "₪" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    { code: "EGP", name: "Egyptian Pound", symbol: "£" },
    { code: "ZAR", name: "South African Rand", symbol: "R" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽" },
    { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł" },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
    { code: "RON", name: "Romanian Leu", symbol: "lei" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { code: "DKK", name: "Danish Krone", symbol: "kr" },
    { code: "ISK", name: "Icelandic Krona", symbol: "kr" },
    { code: "RSD", name: "Serbian Dinar", symbol: "дин" },
    { code: "GEL", name: "Georgian Lari", symbol: "₾" },
    { code: "AMD", name: "Armenian Dram", symbol: "֏" },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
    { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
    { code: "UZS", name: "Uzbekistani Som", symbol: "so'm" },
    { code: "MXN", name: "Mexican Peso", symbol: "$" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    { code: "ARS", name: "Argentine Peso", symbol: "$" },
    { code: "CLP", name: "Chilean Peso", symbol: "$" },
    { code: "COP", name: "Colombian Peso", symbol: "$" },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
    { code: "UYU", name: "Uruguayan Peso", symbol: "$" },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs." },
    { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
    { code: "VES", name: "Venezuelan Bolivar", symbol: "Bs." },
    { code: "CRC", name: "Costa Rican Colon", symbol: "₡" },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
    { code: "JMD", name: "Jamaican Dollar", symbol: "$" },
    { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "TT$" },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
    { code: "HNL", name: "Honduran Lempira", symbol: "L" },
    { code: "NIO", name: "Nicaraguan Cordoba", symbol: "C$" },
    { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
    { code: "KRW", name: "South Korean Won", symbol: "₩" },
    { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
    { code: "THB", name: "Thai Baht", symbol: "฿" },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
    { code: "LAK", name: "Laotian Kip", symbol: "₭" },
    { code: "BND", name: "Brunei Dollar", symbol: "$" },
    { code: "MNT", name: "Mongolian Tugrik", symbol: "₮" },
    { code: "FJD", name: "Fijian Dollar", symbol: "$" },
    { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
    { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
    { code: "XCD", name: "East Caribbean Dollar", symbol: "$" },
  ].sort((a, b) => a.name.localeCompare(b.name));

/** Full IANA time zone list from the runtime, with a curated fallback for older browsers. */
export function getTimezones(): string[] {
  try {
    if (typeof Intl !== "undefined" && "supportedValuesOf" in Intl) {
      const list = (Intl as any).supportedValuesOf("timeZone") as string[];
      if (Array.isArray(list) && list.length > 0) return list;
    }
  } catch {
    /* fall through to the static list below */
  }
  return FALLBACK_TIMEZONES;
}

const FALLBACK_TIMEZONES = [
  "UTC",
  "America/Los_Angeles",
  "America/Denver",
  "America/Chicago",
  "America/New_York",
  "America/Anchorage",
  "America/Sao_Paulo",
  "America/Mexico_City",
  "America/Bogota",
  "America/Toronto",
  "Europe/London",
  "Europe/Lisbon",
  "Europe/Dublin",
  "Europe/Paris",
  "Europe/Berlin",
  "Europe/Madrid",
  "Europe/Rome",
  "Europe/Amsterdam",
  "Europe/Warsaw",
  "Europe/Athens",
  "Europe/Helsinki",
  "Europe/Moscow",
  "Europe/Istanbul",
  "Africa/Cairo",
  "Africa/Lagos",
  "Africa/Johannesburg",
  "Africa/Nairobi",
  "Asia/Dubai",
  "Asia/Riyadh",
  "Asia/Karachi",
  "Asia/Kolkata",
  "Asia/Dhaka",
  "Asia/Kathmandu",
  "Asia/Bangkok",
  "Asia/Jakarta",
  "Asia/Singapore",
  "Asia/Hong_Kong",
  "Asia/Shanghai",
  "Asia/Tokyo",
  "Asia/Seoul",
  "Asia/Manila",
  "Australia/Perth",
  "Australia/Adelaide",
  "Australia/Sydney",
  "Pacific/Auckland",
];

/** BCP-47-ish language codes covering the most widely spoken business languages. */
export const LANGUAGES: Array<{ code: string; name: string }> = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish (Español)" },
  { code: "fr", name: "French (Français)" },
  { code: "de", name: "German (Deutsch)" },
  { code: "it", name: "Italian (Italiano)" },
  { code: "pt", name: "Portuguese (Português)" },
  { code: "nl", name: "Dutch (Nederlands)" },
  { code: "sv", name: "Swedish (Svenska)" },
  { code: "no", name: "Norwegian (Norsk)" },
  { code: "da", name: "Danish (Dansk)" },
  { code: "fi", name: "Finnish (Suomi)" },
  { code: "pl", name: "Polish (Polski)" },
  { code: "cs", name: "Czech (Čeština)" },
  { code: "ro", name: "Romanian (Română)" },
  { code: "el", name: "Greek (Ελληνικά)" },
  { code: "ru", name: "Russian (Русский)" },
  { code: "uk", name: "Ukrainian (Українська)" },
  { code: "tr", name: "Turkish (Türkçe)" },
  { code: "ar", name: "Arabic (العربية)" },
  { code: "he", name: "Hebrew (עברית)" },
  { code: "fa", name: "Persian (فارسی)" },
  { code: "ur", name: "Urdu (اردو)" },
  { code: "hi", name: "Hindi (हिन्दी)" },
  { code: "bn", name: "Bengali (বাংলা)" },
  { code: "ta", name: "Tamil (தமிழ்)" },
  { code: "te", name: "Telugu (తెలుగు)" },
  { code: "mr", name: "Marathi (मराठी)" },
  { code: "gu", name: "Gujarati (ગુજરાતી)" },
  { code: "th", name: "Thai (ไทย)" },
  { code: "vi", name: "Vietnamese (Tiếng Việt)" },
  { code: "id", name: "Indonesian (Bahasa Indonesia)" },
  { code: "ms", name: "Malay (Bahasa Melayu)" },
  { code: "tl", name: "Filipino (Tagalog)" },
  { code: "zh", name: "Chinese, Simplified (简体中文)" },
  { code: "zh-TW", name: "Chinese, Traditional (繁體中文)" },
  { code: "ja", name: "Japanese (日本語)" },
  { code: "ko", name: "Korean (한국어)" },
  { code: "sw", name: "Swahili (Kiswahili)" },
  { code: "am", name: "Amharic (አማርኛ)" },
  { code: "ha", name: "Hausa" },
  { code: "yo", name: "Yoruba" },
  { code: "zu", name: "Zulu" },
  { code: "af", name: "Afrikaans" },
];

/** Legal entity / business structure types covering common worldwide conventions. */
export const BUSINESS_TYPES: Array<{ value: string; label: string }> = [
  { value: "sole_proprietorship", label: "Sole Proprietorship / Freelancer" },
  { value: "partnership", label: "General Partnership" },
  { value: "llp", label: "Limited Liability Partnership (LLP)" },
  { value: "llc", label: "Limited Liability Company (LLC)" },
  {
    value: "private_limited",
    label: "Private Limited Company (Ltd / Pvt Ltd)",
  },
  { value: "public_limited", label: "Public Limited Company (PLC)" },
  { value: "corporation", label: "Corporation (Inc / C-Corp)" },
  { value: "s_corporation", label: "S-Corporation" },
  { value: "cooperative", label: "Cooperative" },
  { value: "trust", label: "Trust" },
  { value: "nonprofit", label: "Non-Profit / NGO" },
  { value: "government", label: "Government Entity" },
  { value: "branch_office", label: "Branch / Representative Office" },
  { value: "holding_company", label: "Holding Company" },
  { value: "joint_venture", label: "Joint Venture" },
  { value: "other", label: "Other" },
];

/** Industry / vertical classification, broad enough to cover most organizations worldwide. */
export const INDUSTRIES: Array<{ value: string; label: string }> = [
  { value: "technology", label: "Technology & Software (SaaS)" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "healthcare", label: "Healthcare & Life Sciences" },
  { value: "pharmaceuticals", label: "Pharmaceuticals & Biotech" },
  { value: "education", label: "Education" },
  { value: "real-estate", label: "Real Estate & Property Management" },
  { value: "construction", label: "Construction & Engineering" },
  { value: "retail", label: "Retail & E-Commerce" },
  { value: "wholesale", label: "Wholesale & Distribution" },
  { value: "services", label: "Professional Services & Consulting" },
  { value: "legal", label: "Legal Services" },
  { value: "finance", label: "Financial Services & Banking" },
  { value: "insurance", label: "Insurance" },
  { value: "agriculture", label: "Agriculture & Farming" },
  { value: "food-beverage", label: "Food & Beverage" },
  { value: "hospitality", label: "Hospitality & Tourism" },
  { value: "transportation", label: "Transportation & Logistics" },
  { value: "automotive", label: "Automotive" },
  { value: "aerospace", label: "Aerospace & Defense" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "media", label: "Media & Entertainment" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "sports", label: "Sports & Recreation" },
  { value: "government", label: "Government & Public Sector" },
  { value: "nonprofit", label: "Non-Profit & NGO" },
  { value: "mining", label: "Mining & Natural Resources" },
  { value: "chemicals", label: "Chemicals" },
  { value: "other", label: "Other" },
];

/**
 * Maps ISO 3166-1 alpha-2 country codes to their primary ISO 4217 currency.
 * Used during registration to auto-select currency when a country is picked.
 */
export const COUNTRY_CURRENCY_MAP: Record<string, string> = {
  US: "USD",
  CA: "CAD",
  MX: "MXN",
  GB: "GBP",
  IE: "EUR",
  FR: "EUR",
  DE: "EUR",
  ES: "EUR",
  IT: "EUR",
  NL: "EUR",
  BE: "EUR",
  AT: "EUR",
  PT: "EUR",
  GR: "EUR",
  FI: "EUR",
  LU: "EUR",
  MT: "EUR",
  CY: "EUR",
  SK: "EUR",
  SI: "EUR",
  EE: "EUR",
  LV: "EUR",
  LT: "EUR",
  HR: "EUR",
  AD: "EUR",
  MC: "EUR",
  SM: "EUR",
  VA: "EUR",
  JP: "JPY",
  CN: "CNY",
  KR: "KRW",
  TW: "TWD",
  HK: "HKD",
  MO: "HKD",
  IN: "INR",
  PK: "PKR",
  BD: "BDT",
  LK: "LKR",
  NP: "NPR",
  AU: "AUD",
  NZ: "NZD",
  FJ: "FJD",
  SG: "SGD",
  MY: "MYR",
  TH: "THB",
  VN: "VND",
  ID: "IDR",
  PH: "PHP",
  KH: "KHR",
  MM: "MMK",
  LA: "LAK",
  BN: "BND",
  MN: "MNT",
  BR: "BRL",
  AR: "ARS",
  CL: "CLP",
  CO: "COP",
  PE: "PEN",
  UY: "UYU",
  BO: "BOB",
  PY: "PYG",
  VE: "VES",
  EC: "USD",
  CR: "CRC",
  DO: "DOP",
  JM: "JMD",
  TT: "TTD",
  GT: "GTQ",
  HN: "HNL",
  NI: "NIO",
  PA: "PAB",
  BS: "USD",
  BB: "USD",
  AE: "AED",
  SA: "SAR",
  QA: "QAR",
  KW: "KWD",
  BH: "BHD",
  OM: "OMR",
  JO: "JOD",
  LB: "LBP",
  IQ: "IQD",
  IL: "ILS",
  TR: "TRY",
  EG: "EGP",
  ZA: "ZAR",
  NG: "NGN",
  KE: "KES",
  GH: "GHS",
  MA: "MAD",
  ET: "ETB",
  TZ: "TZS",
  UG: "UGX",
  RW: "RWF",
  SN: "XOF",
  CI: "XOF",
  CM: "XAF",
  RU: "RUB",
  UA: "UAH",
  PL: "PLN",
  CZ: "CZK",
  HU: "HUF",
  RO: "RON",
  BG: "BGN",
  RS: "RSD",
  SE: "SEK",
  NO: "NOK",
  DK: "DKK",
  IS: "ISK",
  CH: "CHF",
  GE: "GEL",
  AM: "AMD",
  AZ: "AZN",
  KZ: "KZT",
  UZ: "UZS",
};

/** Returns the default currency code for a given country, or 'USD' as fallback. */
export function getDefaultCurrency(countryCode: string): string {
  return COUNTRY_CURRENCY_MAP[countryCode] || "USD";
}

/** Detects the user's timezone from the browser, with 'UTC' as fallback. */
export function getDetectedTimezone(): string {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
  } catch {
    return "UTC";
  }
}

/**
 * Attempts to guess the user's country from their timezone.
 * Returns ISO 3166-1 alpha-2 code or 'US' as fallback.
 */
export function getCountryFromTimezone(tz: string): string {
  const TZ_COUNTRY: Record<string, string> = {
    "America/New_York": "US",
    "America/Chicago": "US",
    "America/Denver": "US",
    "America/Los_Angeles": "US",
    "America/Anchorage": "US",
    "America/Phoenix": "US",
    "America/Toronto": "CA",
    "America/Vancouver": "CA",
    "America/Edmonton": "CA",
    "America/Mexico_City": "MX",
    "America/Bogota": "CO",
    "America/Lima": "PE",
    "America/Sao_Paulo": "BR",
    "America/Argentina/Buenos_Aires": "AR",
    "America/Santiago": "CL",
    "America/Caracas": "VE",
    "Europe/London": "GB",
    "Europe/Dublin": "IE",
    "Europe/Paris": "FR",
    "Europe/Berlin": "DE",
    "Europe/Madrid": "ES",
    "Europe/Rome": "IT",
    "Europe/Amsterdam": "NL",
    "Europe/Brussels": "BE",
    "Europe/Vienna": "AT",
    "Europe/Lisbon": "PT",
    "Europe/Athens": "GR",
    "Europe/Helsinki": "FI",
    "Europe/Warsaw": "PL",
    "Europe/Prague": "CZ",
    "Europe/Budapest": "HU",
    "Europe/Bucharest": "RO",
    "Europe/Sofia": "BG",
    "Europe/Belgrade": "RS",
    "Europe/Stockholm": "SE",
    "Europe/Oslo": "NO",
    "Europe/Copenhagen": "DK",
    "Europe/Zurich": "CH",
    "Europe/Istanbul": "TR",
    "Europe/Moscow": "RU",
    "Europe/Kiev": "UA",
    "Europe/Kyiv": "UA",
    "Asia/Kolkata": "IN",
    "Asia/Calcutta": "IN",
    "Asia/Karachi": "PK",
    "Asia/Dhaka": "BD",
    "Asia/Colombo": "LK",
    "Asia/Kathmandu": "NP",
    "Asia/Dubai": "AE",
    "Asia/Riyadh": "SA",
    "Asia/Doha": "QA",
    "Asia/Kuwait": "KW",
    "Asia/Bahrain": "BH",
    "Asia/Tokyo": "JP",
    "Asia/Shanghai": "CN",
    "Asia/Hong_Kong": "HK",
    "Asia/Seoul": "KR",
    "Asia/Taipei": "TW",
    "Asia/Singapore": "SG",
    "Asia/Kuala_Lumpur": "MY",
    "Asia/Bangkok": "TH",
    "Asia/Jakarta": "ID",
    "Asia/Manila": "PH",
    "Asia/Ho_Chi_Minh": "VN",
    "Africa/Cairo": "EG",
    "Africa/Lagos": "NG",
    "Africa/Johannesburg": "ZA",
    "Africa/Nairobi": "KE",
    "Africa/Accra": "GH",
    "Africa/Casablanca": "MA",
    "Australia/Sydney": "AU",
    "Australia/Melbourne": "AU",
    "Australia/Perth": "AU",
    "Australia/Adelaide": "AU",
    "Australia/Brisbane": "AU",
    "Pacific/Auckland": "NZ",
  };
  return TZ_COUNTRY[tz] || "US";
}
