import { registerModule } from '@unerp/shared/module-registry';

registerModule({
  slug: 'finance',
  title: 'Finance & Accounting',
  icon: 'CreditCard',
  routeSegment: 'finance',
  dashboardRoute: '/finance',
  settingsRoute: undefined,
  nav: [
    { label: 'Dashboard', href: '/finance', icon: 'Home' },
    {
      label: 'Core Accounting',
      isHeader: true,
      items: [
        { label: 'Chart of Accounts', href: '/finance/advanced/chart-of-accounts', icon: 'CreditCard' },
        { label: 'Journal Entries', href: '/finance/advanced/journal-entries', icon: 'FileSliders' },
        { label: 'Financial Periods', href: '/finance/advanced/financial-periods', icon: 'Activity' },
        { label: 'Close Tasks Checklist', href: '/finance/advanced/close-tasks', icon: 'ClipboardCheck' },
        { label: 'Fixed Assets', href: '/finance/advanced/fixed-assets', icon: 'Building2' },
        { label: 'Lease Accounting', href: '/finance/advanced/leases', icon: 'FileText' },
        { label: 'Subscription Billing', href: '/finance/advanced/subscriptions', icon: 'CreditCard' },
        { label: 'Recurring Invoices', href: '/finance/advanced/recurring', icon: 'RefreshCw' },
        { label: 'Revenue Recognition', href: '/finance/advanced/revenue-schedules', icon: 'TrendingUp' },
        { label: 'Dynamic Allocations', href: '/finance/advanced/allocations', icon: 'PieChart' },
      ],
    },
    {
      label: 'Payables & Treasury',
      isHeader: true,
      items: [
        { label: 'Bank Accounts', href: '/finance/advanced/bank-accounts', icon: 'Wallet' },
        { label: 'Bank Reconciliation', href: '/finance/advanced/reconciliations', icon: 'GitFork' },
        { label: 'AP Automation', href: '/finance/advanced/ap-automation', icon: 'ShoppingCart' },
        { label: 'AI Invoice Capture', href: '/finance/advanced/invoice-capture', icon: 'FileText' },
        { label: 'AP Match Rules', href: '/finance/advanced/ap-match-rules', icon: 'ShoppingCart' },
        { label: 'AP Exception Queue', href: '/finance/advanced/exception-queue', icon: 'AlertTriangle' },
        { label: 'Payment Batches', href: '/finance/advanced/payment-batches', icon: 'CreditCard' },
        { label: 'AR Automation', href: '/finance/advanced/ar-automation', icon: 'ClipboardList' },
        { label: 'Treasury & Investments', href: '/finance/advanced/treasury', icon: 'BarChart3' },
        { label: 'Expense Management', href: '/finance/advanced/expense-reports', icon: 'Receipt' },
        { label: 'Expense Policies & Rates', href: '/finance/advanced/expense-policies', icon: 'ShieldCheck' },
        { label: 'Cash Position', href: '/finance/advanced/cash-position', icon: 'DollarSign' },
        { label: 'Cash Flow Forecast', href: '/finance/advanced/cash-flow-forecast', icon: 'Activity' },
      ],
    },
    {
      label: 'Tax & Compliance',
      isHeader: true,
      items: [
        { label: 'Tax Engine', href: '/finance/advanced/tax-engine', icon: 'GitFork' },
        { label: 'Tax Filing', href: '/finance/advanced/tax-filing', icon: 'ShieldAlert' },
        { label: '1099 / Vendor Tax Reporting', href: '/finance/advanced/1099-reporting', icon: 'FileText' },
        { label: 'Economic Nexus Monitoring', href: '/finance/advanced/tax-nexus', icon: 'ShieldAlert' },
        { label: 'Finance Audit Trail', href: '/finance/advanced/audit-logs', icon: 'Eye' },
        { label: 'Account Reconciliation', href: '/finance/advanced/account-reconciliation', icon: 'GitFork' },
      ],
    },
    {
      label: 'Planning & Reporting',
      isHeader: true,
      items: [
        { label: 'Budgeting & Planning', href: '/finance/advanced/budgeting', icon: 'PieChart' },
        { label: 'Budget Scenarios', href: '/finance/advanced/budget-scenarios', icon: 'Layers' },
        { label: 'Scenario Comparison', href: '/finance/advanced/scenario-comparison', icon: 'BarChart3' },
        { label: 'Rolling Forecasts (xP&A)', href: '/finance/advanced/forecast-scenarios', icon: 'TrendingUp' },
        { label: 'Accounting Books (Multi-GAAP)', href: '/finance/advanced/accounting-books', icon: 'BookOpen' },
        { label: 'Financial Reports', href: '/finance/advanced/reports', icon: 'FolderOpen' },
        { label: 'Exchange Rates', href: '/finance/advanced/exchange-rates', icon: 'DollarSign' },
        { label: 'Financial Ratios', href: '/finance/advanced/financial-ratios', icon: 'Scale' },
        { label: 'Consolidation', href: '/finance/advanced/consolidation', icon: 'Building2' },
      ],
    },
  ],
});
