import { registerModule } from '@unerp/shared/module-registry';

registerModule({
  slug: 'inventory',
  title: 'Inventory & Stock',
  icon: 'Package',
  routeSegment: 'inventory',
  dashboardRoute: '/inventory',
  settingsRoute: undefined,
  nav: [
    { label: 'Inventory Dashboard', href: '/inventory', icon: 'Home' },
    { label: 'Products Catalog', href: '/inventory/products', icon: 'Package' },
    { label: 'Warehouse Stock Levels', href: '/inventory/stock-levels', icon: 'Layers' },
    { label: 'Warehouse Directory', href: '/inventory/warehouses', icon: 'Warehouse' },
    {
      label: 'Material Transactions',
      isHeader: true,
      items: [
        { label: 'Stock Entries', href: '/inventory/stock-entries', icon: 'FileText' },
        { label: 'Stock Ledger', href: '/inventory/stock-ledger', icon: 'History' },
        { label: 'Valuation Costing', href: '/inventory/valuations', icon: 'TrendingUp' },
      ],
    },
    {
      label: 'Quality & Control',
      isHeader: true,
      items: [
        { label: 'QA Inspections', href: '/inventory/qa-inspections', icon: 'ShieldCheck' },
        { label: 'Serial Numbers', href: '/inventory/serial-numbers', icon: 'QrCode' },
        { label: 'Batch & Lot Control', href: '/inventory/batches', icon: 'Package' },
      ],
    },
    {
      label: 'Storage & Audit',
      isHeader: true,
      items: [
        { label: 'Bin Configurations', href: '/inventory/bin-locations', icon: 'MapPin' },
        { label: 'Cycle Count Audits', href: '/inventory/cycle-counts', icon: 'ClipboardCheck' },
        { label: 'Cycle Count Schedules', href: '/inventory/cycle-count-schedules', icon: 'ClipboardCheck' },
        { label: 'License Plates & Put-away', href: '/inventory/license-plates', icon: 'Package' },
        { label: 'Traceability', href: '/inventory/traceability', icon: 'QrCode' },
        { label: 'Stock Reservations & Analytics', href: '/inventory/stock-reservations', icon: 'ClipboardCheck' },
        { label: 'Kits & Assembly', href: '/inventory/kits', icon: 'Package' },
        { label: 'Transfer Approvals', href: '/inventory/transfer-approvals', icon: 'ShieldCheck' },
        { label: 'Movement History & Labels', href: '/inventory/movement-history', icon: 'ClipboardCheck' },
        { label: 'Wave Picking', href: '/inventory/pick-waves', icon: 'Truck' },
        { label: 'Mobile Scan Pick/Pack', href: '/inventory/mobile-pick', icon: 'Smartphone' },
        { label: 'Consignment Inventory', href: '/inventory/consignment', icon: 'Truck' },
        { label: 'Reorder Rules & Automation', href: '/inventory/reorder-rules', icon: 'ShoppingCart' },
        { label: 'QA Templates & Routing', href: '/inventory/qa-templates', icon: 'ShieldCheck' },
        { label: 'Expiry, FEFO & Recalls', href: '/inventory/expiry-fefo', icon: 'AlertTriangle' },
        { label: 'Cross-Docking', href: '/inventory/cross-dock', icon: 'Link' },
        { label: 'Slotting Optimization', href: '/inventory/slotting', icon: 'MapPin' },
        { label: 'Dock Scheduling', href: '/inventory/dock-scheduling', icon: 'Truck' },
        { label: 'Demand Forecasting', href: '/inventory/demand-forecasting', icon: 'TrendingUp' },
        { label: 'Returns to Vendor (RTV)', href: '/inventory/rtv', icon: 'RotateCcw' },
        { label: 'Labor Management', href: '/inventory/labor-management', icon: 'Users' },
        { label: 'Supplier Quality', href: '/inventory/supplier-quality', icon: 'ClipboardList' },
        { label: 'Automation Rules', href: '/inventory/automation-rules', icon: 'Zap' },
        { label: 'Inventory Analytics', href: '/inventory/inventory-analytics', icon: 'BarChart3' },
        { label: 'Logistics & Shipping', href: '/inventory/logistics', icon: 'Truck' },
        { label: 'Quality & Compliance', href: '/inventory/quality-compliance', icon: 'ShieldCheck' },
        { label: 'Warehouse Operations', href: '/inventory/warehouse-ops', icon: 'Truck' },
        { label: 'Lot & Serial Tracking', href: '/inventory/lot-serial', icon: 'ClipboardList' },
        { label: 'Landed Cost', href: '/inventory/landed-cost', icon: 'Calculator' },
        { label: 'Stock Valuation', href: '/inventory/stock-valuation', icon: 'DollarSign' },
        { label: 'Transfer Orders', href: '/inventory/transfer-orders', icon: 'Truck' },
        { label: 'Yard Management', href: '/inventory/yard-management', icon: 'Truck' },
        { label: 'Stock Takes', href: '/inventory/stock-takes', icon: 'ClipboardList' },
        { label: 'Hazmat', href: '/inventory/hazmat', icon: 'AlertTriangle' },
        { label: 'Approved Suppliers', href: '/inventory/asl', icon: 'CheckSquare' },
        { label: 'Container & Pallets', href: '/inventory/container-pallet', icon: 'Package' },
        { label: 'Catch-Weight & Recall', href: '/inventory/catch-weight-recall', icon: 'AlertTriangle' },
        { label: 'Packaging & GS1', href: '/inventory/packaging-gs1', icon: 'Layers' },
        { label: 'Cold Chain & Write-Off', href: '/inventory/cold-chain-writeoff', icon: 'Box' },
        { label: 'Velocity & ABC-XYZ', href: '/inventory/velocity-abc-xyz', icon: 'TrendingUp' },
        { label: 'Customer Returns', href: '/inventory/customer-returns', icon: 'Package' },
        { label: 'Min-Max Replenishment', href: '/inventory/minmax-replen', icon: 'TrendingUp' },
        { label: 'Freight Claims', href: '/inventory/freight-claims', icon: 'AlertTriangle' },
        { label: 'Vendor-Managed Inventory', href: '/inventory/vmi', icon: 'Box' },
        { label: 'Inventory Costing', href: '/inventory/costing', icon: 'TrendingUp' },
        { label: 'Lot/Batch Expiry', href: '/inventory/lot-expiry', icon: 'AlertTriangle' },
        { label: 'Demand Forecasting', href: '/inventory/demand-forecasting', icon: 'TrendingUp' },
      ],
    },
    {
      label: 'System & Configuration',
      isHeader: true,
      items: [
        { label: 'Advanced Hub', href: '/inventory/advanced', icon: 'Settings' },
      ],
    },
  ],
});
