// @ts-nocheck
"use client";

import {
  Briefcase,
  Target,
  Home,
  Clock,
  Activity,
  DollarSign,
  BarChart3,
  Layers,
  Sprout,
  BookOpen,
  TrendingUp,
  Building2,
  Scale,
  LayoutDashboard,
  MessageSquare,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui-layout";

export {
  ModuleTabLayout as ProjectsTabLayout,
  type ModuleTab as ProjectTab,
  type ModuleTabLayoutProps as ProjectsTabLayoutProps,
  SubTabBar,
  type SubTab,
} from "@unerp/ui-layout";

export const PROJECTS_TABS: ModuleTab[] = [
  {
    id: "overview",
    label: "Gantt & Tasks",
    href: "/projects",
    icon: Briefcase,
    description: "Project Gantt charts and task management",
  },
  {
    id: "portfolios",
    label: "Portfolio Hub",
    href: "/projects/portfolios",
    icon: Target,
    description: "Project portfolio overview",
  },
  {
    id: "programs",
    label: "Programs",
    href: "/projects/programs",
    icon: Layers,
    description: "Program governance, benefits, and financials",
  },
  {
    id: "agile",
    label: "Agile / Scrum",
    href: "/projects/agile",
    icon: Sprout,
    description: "Sprints, backlog, velocity, and burndown",
  },
  {
    id: "client-portal",
    label: "Client Portal",
    href: "/projects/client-portal",
    icon: Home,
    description: "Client-facing project portal",
  },
  {
    id: "workloads",
    label: "Resource Workloads",
    href: "/projects/workloads",
    icon: Clock,
    description: "Resource allocation and workloads",
  },
  {
    id: "health",
    label: "Project Health",
    href: "/projects/health",
    icon: Activity,
    description: "CPM and project health metrics",
  },
  {
    id: "skills",
    label: "Resource Skills",
    href: "/projects/resource-skills",
    icon: BookOpen,
    description: "Skills inventory, certifications, and gap analysis",
    advanced: true,
    group: "Advanced",
  },
  {
    id: "advanced-evm",
    label: "Advanced EVM",
    href: "/projects/advanced-evm",
    icon: TrendingUp,
    description: "EAC, TCPI, forecasting, and KPI tracking",
    advanced: true,
    group: "Advanced",
  },
  {
    id: "capex",
    label: "CAPEX",
    href: "/projects/capex",
    icon: Building2,
    description: "Capital expenditure, budgets, and capitalization",
    advanced: true,
    group: "Advanced",
  },
  {
    id: "claims",
    label: "Claims & Changes",
    href: "/projects/claims",
    icon: Scale,
    description: "Claims, variation orders, and dispute resolution",
    advanced: true,
    group: "Advanced",
  },
  {
    id: "pmo",
    label: "PMO Dashboard",
    href: "/projects/pmo",
    icon: LayoutDashboard,
    description: "Governance, scorecards, stage gates, and compliance",
    advanced: true,
    group: "Analytics",
  },
  {
    id: "revenue",
    label: "Revenue Recognition",
    href: "/projects/revenue-recognition",
    icon: DollarSign,
    description: "Revenue recognition and WIP",
  },
  {
    id: "collaboration",
    label: "Collaboration",
    href: "/projects/collaboration",
    icon: MessageSquare,
    description: "Discussions, reviews, feed, and wiki",
    advanced: true,
    group: "Advanced",
  },
  {
    id: "timesheets",
    label: "Timesheets",
    href: "/projects/timesheets",
    icon: Clock,
    description: "Timesheet entry and approval",
  },
  {
    id: "reports",
    label: "Reports",
    href: "/projects/reports",
    icon: BarChart3,
    advanced: true,
    group: "Analytics",
    description: "Project reports and dashboards",
  },
  {
    id: "wip-reports",
    label: "WIP & Job Costing",
    href: "/projects/wip-reports",
    icon: DollarSign,
    advanced: true,
    group: "Analytics",
    description: "Work-in-progress and job costing reports",
  },
];
