'use client';

import React, { useState, useEffect } from 'react';
import { FileText, Download, Eye, Trash2, Plus, RefreshCw, Search } from 'lucide-react';
import { RouteGuard, useApiClient } from '@unerp/framework';
import styles from './page.module.css';

interface GeneratedDocument {
  id: string;
  name: string;
  templateName: string;
  format: string;
  generatedAt: string;
  generatedBy: string;
  size: string;
  entityType: string;
  entityId: string;
}

export default function DriveTemplatesPage() {
  const client = useApiClient();
  const [documents, setDocuments] = useState<GeneratedDocument[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    const loadDocuments = async () => {
      try {
        const data = await client.get<GeneratedDocument[] | { data?: GeneratedDocument[] }>('/storage/generated-documents');
        setDocuments(Array.isArray(data) ? data : (data.data || []));
      } catch {
        // Fallback data when API unavailable
        setDocuments([
          { id: 'gd-1', name: 'Invoice-2026-0185.pdf', templateName: 'Invoice Template', format: 'PDF', generatedAt: '2026-06-21 09:15', generatedBy: 'Admin', size: '142 KB', entityType: 'Invoice', entityId: 'INV-2026-0185' },
          { id: 'gd-2', name: 'PO-2026-0284.pdf', templateName: 'Purchase Order Template', format: 'PDF', generatedAt: '2026-06-20 14:30', generatedBy: 'Jane Smith', size: '98 KB', entityType: 'PurchaseOrder', entityId: 'PO-2026-0284' },
          { id: 'gd-3', name: 'Payslip-Jun-2026-EMP001.pdf', templateName: 'Payslip Template', format: 'PDF', generatedAt: '2026-06-15 08:00', generatedBy: 'System', size: '78 KB', entityType: 'Payslip', entityId: 'PS-2026-0601' },
          { id: 'gd-4', name: 'Contract-WayneCorp.pdf', templateName: 'Service Agreement', format: 'PDF', generatedAt: '2026-06-14 16:45', generatedBy: 'Legal Team', size: '256 KB', entityType: 'Contract', entityId: 'CON-2026-0042' },
          { id: 'gd-5', name: 'SalesQuote-Q3-Acme.pdf', templateName: 'Quotation Template', format: 'PDF', generatedAt: '2026-06-13 11:20', generatedBy: 'Sales Team', size: '124 KB', entityType: 'Quotation', entityId: 'QT-2026-0198' },
        ]);
      } finally {
        setLoading(false);
      }
    };
    loadDocuments();
  }, [client]);

  const filtered = documents.filter(d =>
    d.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    d.templateName.toLowerCase().includes(searchQuery.toLowerCase()) ||
    d.entityId.toLowerCase().includes(searchQuery.toLowerCase())
  );

  if (loading) {
    return (
      <div className={styles.p1}>
        <RefreshCw className="animate-spin ui-text-primary" size={32} />
      </div>
    );
  }

  return (
    <RouteGuard permission="drive.templates.read">
    <div className="ui-stack-6">
      <div>
        <h1 className="text-2xl ui-hstack-2">
          <FileText className="ui-text-primary" />
          Generated Documents
        </h1>
        <p className="ui-text-sm-muted">
          Browse and download PDFs generated from document templates (invoices, purchase orders, payslips, contracts).
        </p>
      </div>

      <div className={styles.p2}>
        <div className={styles.p3}>
          <Search size={16} className={styles.p4} />
          <input
            type="text"
            placeholder="Search documents, templates, entity IDs..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            className={styles.p5}
          />
        </div>
        <button className={styles.p6}>
          <Plus size={16} /> Generate New
        </button>
      </div>

      <div className={styles.p7}>
        <table className={styles.p8}>
          <thead>
            <tr className={styles.p9}>
              {['Document', 'Template', 'Entity', 'Generated By', 'Date', 'Size', 'Actions'].map(h => (
                <th key={h} className={styles.p10}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.map(doc => (
              <tr key={doc.id} className="border-b">
                <td className="py-3 px-4">
                  <div className="ui-hstack-2">
                    <FileText size={16} className={styles.p11} />
                    <span className="font-semibold">{doc.name}</span>
                  </div>
                </td>
                <td className={styles.p12}>{doc.templateName}</td>
                <td className="py-3 px-4">
                  <span className={styles.p13}>{doc.entityId}</span>
                </td>
                <td className={styles.p14}>{doc.generatedBy}</td>
                <td className={styles.p15}>{doc.generatedAt}</td>
                <td className={styles.p16}>{doc.size}</td>
                <td className="py-3 px-4">
                  <div className="ui-flex ui-gap-1">
                    <button className={styles.p17}><Eye size={14} /></button>
                    <button className={styles.p18}><Download size={14} /></button>
                    <button className={styles.p19}><Trash2 size={14} /></button>
                  </div>
                </td>
              </tr>
            ))}
            {filtered.length === 0 && (
              <tr>
                <td colSpan={7} className={styles.p20}>
                  No generated documents found matching your search.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
    </RouteGuard>
  );
}
