"use client";

import {
  Store,
  ShoppingCart,
  Users,
  BarChart3,
  Activity,
  Clock,
  Percent,
  Settings,
  DollarSign,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui/layout";

export {
  ModuleTabLayout as PosTabLayout,
  type ModuleTab as PosTab,
  type ModuleTabLayoutProps as PosTabLayoutProps,
  SubTabBar,
  type SubTab,
} from "@unerp/ui/layout";

export const POS_TABS: ModuleTab[] = [
  {
    id: "terminal",
    label: "POS Terminal",
    href: "/pos",
    icon: Store,
    description: "Point of sale terminal",
  },
  {
    id: "orders",
    label: "POS Orders",
    href: "/pos/orders",
    icon: ShoppingCart,
    description: "POS order history",
  },
  {
    id: "customers",
    label: "Customers & Loyalty",
    href: "/pos/customers",
    icon: Users,
    description: "Customer management and loyalty",
  },
  {
    id: "reports",
    label: "Sales Analytics",
    href: "/pos/reports",
    icon: BarChart3,
    description: "POS sales analytics",
  },
  {
    id: "advanced",
    label: "Advanced Features",
    href: "/pos/advanced",
    icon: Activity,
    description: "Advanced POS configuration",
  },
  {
    id: "registers",
    label: "Registers",
    href: "/pos/registers",
    icon: Store,
    advanced: true,
    group: "Retail Tools",
    description: "POS terminal registers management",
  },
  {
    id: "shifts",
    label: "Shifts & Cash Drawers",
    href: "/pos/shifts",
    icon: Clock,
    advanced: true,
    group: "Retail Tools",
    description: "Cashier shifts and till reconciliation",
  },
  {
    id: "held-orders",
    label: "Held Orders",
    href: "/pos/held-orders",
    icon: Clock,
    advanced: true,
    group: "Retail Tools",
    description: "Parked and held carts",
  },
  {
    id: "promotions",
    label: "Promotions",
    href: "/pos/promotions",
    icon: Percent,
    advanced: true,
    group: "Retail Tools",
    description: "Promotions engine",
  },
  {
    id: "discount-rules",
    label: "Discount Rules",
    href: "/pos/discount-rules",
    icon: Percent,
    advanced: true,
    group: "Retail Tools",
    description: "Custom discount rules and override policies",
  },
  {
    id: "gift-cards",
    label: "Gift Cards",
    href: "/pos/gift-cards",
    icon: DollarSign,
    advanced: true,
    group: "Retail Tools",
    description: "Gift card issuance and redemptions",
  },
  {
    id: "kitchen-display",
    label: "Kitchen Display (KDS)",
    href: "/pos/kitchen-display",
    icon: Activity,
    advanced: true,
    group: "Retail Tools",
    description: "Live kitchen order fulfillment status",
  },
  {
    id: "refunds",
    label: "Refunds & Returns",
    href: "/pos/refunds",
    icon: ShoppingCart,
    advanced: true,
    group: "Retail Tools",
    description: "POS order refunds and inventory restock",
  },
  {
    id: "split-payments",
    label: "Split Payments",
    href: "/pos/split-payments",
    icon: DollarSign,
    advanced: true,
    group: "Retail Tools",
    description: "Multi-tender and split payment options",
  },
  {
    id: "order-types",
    label: "Order Types",
    href: "/pos/order-types",
    icon: Settings,
    advanced: true,
    group: "Customizer",
    description: "Dine-in, takeout, delivery order types",
  },
  {
    id: "tax-rules",
    label: "POS Tax Rules",
    href: "/pos/tax-rules",
    icon: Settings,
    advanced: true,
    group: "Customizer",
    description: "Tax rates and regional overrides",
  },
  {
    id: "layaway",
    label: "Layaway Plans",
    href: "/pos/layaway",
    icon: DollarSign,
    advanced: true,
    group: "Retail Tools",
    description: "Layaway plan management",
  },
  {
    id: "designer",
    label: "Receipt Designer",
    href: "/pos/designer",
    icon: Settings,
    advanced: true,
    group: "Customizer",
    description: "Receipt layout designer",
  },
  {
    id: "diagnostics",
    label: "Printer Diagnostics",
    href: "/pos/diagnostics",
    icon: Activity,
    advanced: true,
    group: "Customizer",
    description: "Printer and hardware diagnostics",
  },
  {
    id: "settings",
    label: "POS Settings",
    href: "/pos/settings",
    icon: Settings,
    advanced: true,
    group: "Customizer",
    description: "Global POS module settings",
  },
];
