"use client";

import {
  Users,
  UserIcon,
  Briefcase,
  UserPlus,
  UserMinus,
  Award,
  Clock,
  DollarSign,
  Coffee,
  GraduationCap,
  CreditCard,
  BarChart3,
  FileText,
  Target,
  Star,
  MessageSquare,
  TrendingUp,
  CalendarDays,
  Monitor,
  ClipboardCheck,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui-layout";

export {
  ModuleTabLayout as HrTabLayout,
  type ModuleTab as HrTab,
  type ModuleTabLayoutProps as HrTabLayoutProps,
  SubTabBar,
  type SubTab,
} from "@unerp/ui-layout";

export const HR_TABS: ModuleTab[] = [
  {
    id: "overview",
    label: "Dashboard",
    href: "/hr",
    icon: Users,
    description: "Employee directory and HR overview",
  },
  {
    id: "self-service",
    label: "Self-Service",
    href: "/hr/advanced/self-service",
    icon: UserIcon,
    description: "Employee self-service portal",
  },
  {
    id: "recruitment",
    label: "Recruitment",
    href: "/hr/advanced/recruitment",
    icon: Briefcase,
    description: "Job postings and candidate tracking",
  },
  {
    id: "onboarding",
    label: "Onboarding",
    href: "/hr/advanced/onboarding",
    icon: UserPlus,
    description: "New hire onboarding checklists",
  },
  {
    id: "performance",
    label: "Performance",
    href: "/hr/advanced/appraisals",
    icon: Award,
    description: "Goals, appraisals, and 360 feedback",
  },
  {
    id: "attendance",
    label: "Attendance",
    href: "/hr/advanced/attendance",
    icon: Clock,
    description: "Attendance records and shift scheduling",
  },
  {
    id: "payroll",
    label: "Payroll",
    href: "/hr/advanced/payroll",
    icon: DollarSign,
    description: "Payroll and salary management",
  },
  {
    id: "leaves",
    label: "Leaves",
    href: "/hr/advanced/leaves",
    icon: Coffee,
    description: "Leave requests and accruals",
  },
  {
    id: "training",
    label: "Training",
    href: "/hr/advanced/trainings",
    icon: GraduationCap,
    description: "Training and certifications",
  },
  {
    id: "benefits",
    label: "Benefits",
    href: "/hr/advanced/benefits",
    icon: CreditCard,
    description: "Benefits administration",
  },
  {
    id: "analytics",
    label: "Analytics",
    href: "/hr/advanced/analytics",
    icon: BarChart3,
    description: "Workforce analytics",
  },
  {
    id: "documents",
    label: "Documents",
    href: "/hr/advanced/documents",
    icon: FileText,
    advanced: true,
    group: "Admin",
    description: "HR document manager",
  },
  {
    id: "offboarding",
    label: "Offboarding",
    href: "/hr/advanced/offboarding",
    icon: UserMinus,
    advanced: true,
    group: "Talent",
    description: "Offboarding checklists",
  },
  {
    id: "goals",
    label: "Goals & OKRs",
    href: "/hr/advanced/goals",
    icon: Target,
    advanced: true,
    group: "Talent",
    description: "Goals and OKRs",
  },
  {
    id: "skills",
    label: "Skills Matrix",
    href: "/hr/advanced/skills",
    icon: Star,
    advanced: true,
    group: "Talent",
    description: "Employee skills matrix",
  },
  {
    id: "feedback",
    label: "360° Feedback",
    href: "/hr/advanced/feedback",
    icon: MessageSquare,
    advanced: true,
    group: "Talent",
    description: "360 degree feedback",
  },
  {
    id: "succession",
    label: "Succession Plan",
    href: "/hr/advanced/succession",
    icon: TrendingUp,
    advanced: true,
    group: "Talent",
    description: "Succession planning",
  },
  {
    id: "shifts",
    label: "Shift Scheduling",
    href: "/hr/advanced/shifts",
    icon: CalendarDays,
    advanced: true,
    group: "Operations",
    description: "Shift scheduling",
  },
  {
    id: "operations-service",
    label: "Operations & Service Hub",
    href: "/hr/advanced/operations-service",
    icon: Monitor,
    advanced: true,
    group: "Operations",
    description: "Operations and service hub",
  },
  {
    id: "positions",
    label: "Position Control",
    href: "/hr/advanced/positions",
    icon: ClipboardCheck,
    advanced: true,
    group: "Operations",
    description: "Position control",
  },
];
