"use client";

import {
  Package,
  Layers,
  Warehouse,
  FileText,
  ShieldCheck,
  ClipboardList,
  Truck,
  ArrowLeftRight,
  BarChart3,
  RotateCcw,
  Settings,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui-layout";

export {
  ModuleTabLayout as InventoryTabLayout,
  type ModuleTab as InventoryTab,
  type ModuleTabLayoutProps as InventoryTabLayoutProps,
  SubTabBar,
  type SubTab,
} from "@unerp/ui-layout";

export const INVENTORY_TABS: ModuleTab[] = [
  // ---- Primary ----
  {
    id: "overview",
    label: "Dashboard",
    href: "/inventory",
    icon: Package,
    description: "Stock summary, warehouse KPIs, and inventory turnover",
  },
  {
    id: "products",
    label: "Products Catalog",
    href: "/inventory/products",
    icon: Package,
    description: "Item master, SKUs, categories, and product variants",
  },
  {
    id: "stock-levels",
    label: "Stock Levels",
    href: "/inventory/stock-levels",
    icon: Layers,
    description: "Real-time stock on-hand, reserved, and available quantities",
  },
  {
    id: "warehouses",
    label: "Warehouses",
    href: "/inventory/warehouses",
    icon: Warehouse,
    description: "Warehouse locations, bin configurations, and storage zones",
  },
  {
    id: "stock-entries",
    label: "Material Transactions",
    href: "/inventory/stock-entries",
    icon: FileText,
    description: "Stock transfers, receipts, issues, and material adjustments",
  },

  // ---- Quality & Traceability ----
  {
    id: "batches",
    label: "Batch Tracking",
    href: "/inventory/batches",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Batch/lot numbers, expiry dates, and usage status",
  },
  {
    id: "lot-serial",
    label: "Lot & Serial Tracking",
    href: "/inventory/lot-serial",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Lot and serial number genealogy",
  },
  {
    id: "serial-numbers",
    label: "Serial Numbers",
    href: "/inventory/serial-numbers",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Serialized unit tracking and warranty status",
  },
  {
    id: "lot-expiry",
    label: "Lot Expiry",
    href: "/inventory/lot-expiry",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Lot expiration monitoring and alerts",
  },
  {
    id: "expiry-fefo",
    label: "Expiry & FEFO",
    href: "/inventory/expiry-fefo",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "First-Expired-First-Out picking policy",
  },
  {
    id: "catch-weight-recall",
    label: "Catch Weight & Recall",
    href: "/inventory/catch-weight-recall",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Catch-weight items and recall management",
  },
  {
    id: "cold-chain-writeoff",
    label: "Cold Chain Write-off",
    href: "/inventory/cold-chain-writeoff",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Cold-chain excursion tracking and write-offs",
  },
  {
    id: "hazmat",
    label: "Hazmat Compliance",
    href: "/inventory/hazmat",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Hazardous material classifications and compliance",
  },
  {
    id: "supplier-quality",
    label: "Supplier Quality",
    href: "/inventory/supplier-quality",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Vendor scorecards and quality metrics",
  },
  {
    id: "qa-inspections",
    label: "QA Inspections",
    href: "/inventory/qa-inspections",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Quality assurance inspection records",
  },
  {
    id: "qa-templates",
    label: "QA Templates",
    href: "/inventory/qa-templates",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Inspection and quality check templates",
  },
  {
    id: "quality-compliance",
    label: "Quality & Compliance",
    href: "/inventory/quality-compliance",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "Compliance holds and quality dispositions",
  },
  {
    id: "traceability",
    label: "Traceability",
    href: "/inventory/traceability",
    icon: ShieldCheck,
    advanced: true,
    group: "Quality & Traceability",
    description: "End-to-end lot/serial traceability chain",
  },

  // ---- Counting & Storage ----
  {
    id: "cycle-counts",
    label: "Cycle Counts",
    href: "/inventory/cycle-counts",
    icon: ClipboardList,
    advanced: true,
    group: "Counting & Storage",
    description: "Cycle count execution and variance review",
  },
  {
    id: "cycle-count-schedules",
    label: "Cycle Count Schedules",
    href: "/inventory/cycle-count-schedules",
    icon: ClipboardList,
    advanced: true,
    group: "Counting & Storage",
    description: "Recurring cycle count scheduling",
  },
  {
    id: "stock-takes",
    label: "Stock Takes",
    href: "/inventory/stock-takes",
    icon: ClipboardList,
    advanced: true,
    group: "Counting & Storage",
    description: "Full physical inventory stock takes",
  },
  {
    id: "license-plates",
    label: "License Plates",
    href: "/inventory/license-plates",
    icon: ClipboardList,
    advanced: true,
    group: "Counting & Storage",
    description: "LPN tracking and configuration",
  },
  {
    id: "bin-locations",
    label: "Bin Locations",
    href: "/inventory/bin-locations",
    icon: ClipboardList,
    advanced: true,
    group: "Counting & Storage",
    description: "Bin-level storage locations",
  },
  {
    id: "slotting",
    label: "Slotting",
    href: "/inventory/slotting",
    icon: ClipboardList,
    advanced: true,
    group: "Counting & Storage",
    description: "Warehouse slotting optimization",
  },

  // ---- Warehouse Operations ----
  {
    id: "warehouse-ops",
    label: "Warehouse Operations",
    href: "/inventory/warehouse-ops",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "Inbound/outbound operations control tower",
  },
  {
    id: "dock-scheduling",
    label: "Dock Scheduling",
    href: "/inventory/dock-scheduling",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "Dock door appointment scheduling",
  },
  {
    id: "cross-dock",
    label: "Cross-Dock",
    href: "/inventory/cross-dock",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "Cross-docking flow-through management",
  },
  {
    id: "yard-management",
    label: "Yard Management",
    href: "/inventory/yard-management",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "Trailer and yard spot management",
  },
  {
    id: "labor-management",
    label: "Labor Management",
    href: "/inventory/labor-management",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "Warehouse labor tracking and productivity",
  },
  {
    id: "mobile-pick",
    label: "Mobile Pick",
    href: "/inventory/mobile-pick",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "Mobile picking device workflows",
  },
  {
    id: "pick-waves",
    label: "Pick Waves",
    href: "/inventory/pick-waves",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "Wave planning and release",
  },
  {
    id: "container-pallet",
    label: "Container & Pallet",
    href: "/inventory/container-pallet",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "Container and pallet build management",
  },
  {
    id: "packaging-gs1",
    label: "Packaging & GS1",
    href: "/inventory/packaging-gs1",
    icon: Truck,
    advanced: true,
    group: "Warehouse Operations",
    description: "GS1 labeling and packaging hierarchy",
  },

  // ---- Transfers & Logistics ----
  {
    id: "transfer-orders",
    label: "Transfer Orders",
    href: "/inventory/transfer-orders",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "Inter-warehouse stock transfer orders",
  },
  {
    id: "transfer-approvals",
    label: "Transfer Approvals",
    href: "/inventory/transfer-approvals",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "Approval workflow for stock transfers",
  },
  {
    id: "shipment-tracking",
    label: "Shipment Tracking",
    href: "/inventory/shipment-tracking",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "Outbound shipment tracking",
  },
  {
    id: "logistics",
    label: "Logistics",
    href: "/inventory/logistics",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "Carrier and freight logistics management",
  },
  {
    id: "freight-claims",
    label: "Freight Claims",
    href: "/inventory/freight-claims",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "Freight damage/loss claim tracking",
  },
  {
    id: "asn",
    label: "ASN (Advance Ship Notice)",
    href: "/inventory/asn",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "Inbound advance ship notices",
  },
  {
    id: "asl",
    label: "Approved Supplier List",
    href: "/inventory/asl",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "Approved supplier list per item",
  },
  {
    id: "vmi",
    label: "Vendor-Managed Inventory",
    href: "/inventory/vmi",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "VMI agreements and replenishment",
  },
  {
    id: "consignment",
    label: "Consignment",
    href: "/inventory/consignment",
    icon: ArrowLeftRight,
    advanced: true,
    group: "Transfers & Logistics",
    description: "Consignment stock ownership tracking",
  },

  // ---- Analytics & Planning ----
  {
    id: "inventory-analytics",
    label: "Inventory Analytics",
    href: "/inventory/inventory-analytics",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Inventory KPIs and trend analytics",
  },
  {
    id: "demand-forecasting",
    label: "Demand Forecasting",
    href: "/inventory/demand-forecasting",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Statistical demand forecasting",
  },
  {
    id: "velocity-abc-xyz",
    label: "Velocity ABC/XYZ",
    href: "/inventory/velocity-abc-xyz",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "ABC/XYZ velocity classification",
  },
  {
    id: "minmax-replen",
    label: "Min/Max Replenishment",
    href: "/inventory/minmax-replen",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Min/max replenishment planning",
  },
  {
    id: "reorder-rules",
    label: "Reorder Rules",
    href: "/inventory/reorder-rules",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Reorder point and quantity rules",
  },
  {
    id: "automation-rules",
    label: "Automation Rules",
    href: "/inventory/automation-rules",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Automated inventory action rules",
  },
  {
    id: "costing",
    label: "Costing",
    href: "/inventory/costing",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Inventory costing methods and history",
  },
  {
    id: "landed-cost",
    label: "Landed Cost",
    href: "/inventory/landed-cost",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Landed cost allocation for receipts",
  },
  {
    id: "valuations",
    label: "Valuations",
    href: "/inventory/valuations",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Inventory valuation reporting",
  },
  {
    id: "stock-valuation",
    label: "Stock Valuation",
    href: "/inventory/stock-valuation",
    icon: BarChart3,
    advanced: true,
    group: "Analytics & Planning",
    description: "Point-in-time stock valuation",
  },

  // ---- Returns & Movement ----
  {
    id: "customer-returns",
    label: "Customer Returns",
    href: "/inventory/customer-returns",
    icon: RotateCcw,
    advanced: true,
    group: "Returns & Movement",
    description: "Customer return receipts and disposition",
  },
  {
    id: "rtv",
    label: "Returns to Vendor",
    href: "/inventory/rtv",
    icon: RotateCcw,
    advanced: true,
    group: "Returns & Movement",
    description: "Vendor RMA requests and return shipments",
  },
  {
    id: "movement-history",
    label: "Movement History",
    href: "/inventory/movement-history",
    icon: RotateCcw,
    advanced: true,
    group: "Returns & Movement",
    description: "Full stock movement audit trail",
  },
  {
    id: "stock-reservations",
    label: "Stock Reservations",
    href: "/inventory/stock-reservations",
    icon: RotateCcw,
    advanced: true,
    group: "Returns & Movement",
    description: "Reserved stock allocations",
  },
  {
    id: "stock-ledger",
    label: "Stock Ledger",
    href: "/inventory/stock-ledger",
    icon: RotateCcw,
    advanced: true,
    group: "Returns & Movement",
    description: "Chronological stock ledger entries",
  },

  // ---- Settings ----
  {
    id: "settings",
    label: "Settings",
    href: "/inventory/settings",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Item categories, reorder rules, and valuation policies",
  },
  {
    id: "advanced",
    label: "Advanced Configuration",
    href: "/inventory/advanced",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Categories, UoM, reorder rules, and kit configuration",
  },
  {
    id: "kits",
    label: "Kits & Bundles",
    href: "/inventory/kits",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Product kit and bundle definitions",
  },
];
