// @ts-nocheck
"use client";

import {
  PieChart,
  LayoutDashboard,
  LayoutGrid,
  ShieldAlert,
  GitFork,
  Layers,
  TrendingUp,
  BarChart3,
  FileText,
  Activity,
  FileDown,
  Settings,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui-layout";

export {
  ModuleTabLayout as AnalyticsTabLayout,
  type ModuleTab as AnalyticsTab,
  type ModuleTabLayoutProps as AnalyticsTabLayoutProps,
  SubTabBar,
  type SubTab,
} from "@unerp/ui-layout";

export const ANALYTICS_TABS: ModuleTab[] = [
  {
    id: "overview",
    label: "Dashboard",
    href: "/analytics",
    icon: PieChart,
    description: "BI analytics dashboard",
  },
  {
    id: "builder",
    label: "Dashboard Builder",
    href: "/analytics/builder",
    icon: LayoutDashboard,
    description: "Custom dashboard builder",
  },
  {
    id: "insights",
    label: "Smart Insights",
    href: "/analytics/insights",
    icon: ShieldAlert,
    description: "AI-powered insights",
  },
  {
    id: "query",
    label: "Visual Query Builder",
    href: "/analytics/query",
    icon: GitFork,
    description: "Visual query building",
  },
  {
    id: "pivot",
    label: "Pivot Matrix",
    href: "/analytics/pivot",
    icon: Layers,
    description: "Pivot table aggregator",
  },
  {
    id: "predictive",
    label: "Predictive Analytics",
    href: "/analytics/predictive",
    icon: TrendingUp,
    description: "Predictive analytics",
  },
  {
    id: "dashboards",
    label: "Saved Dashboards",
    href: "/analytics/dashboards",
    icon: LayoutGrid,
    description: "Saved dashboard views",
    advanced: true,
    group: "More Analytics",
  },
  {
    id: "advanced",
    label: "Advanced BI",
    href: "/analytics/advanced",
    icon: BarChart3,
    description: "Advanced BI analytics",
    advanced: true,
    group: "More Analytics",
  },
  {
    id: "reports",
    label: "Saved Reports",
    href: "/analytics/reports",
    icon: FileText,
    description: "Saved report library",
    advanced: true,
    group: "More Analytics",
  },
  {
    id: "kpis",
    label: "KPI Dashboard",
    href: "/analytics/kpis",
    icon: Activity,
    description: "KPI tracking dashboard",
    advanced: true,
    group: "More Analytics",
  },
  {
    id: "exports",
    label: "Scheduled Exports",
    href: "/analytics/exports",
    icon: FileDown,
    description: "Scheduled report exports",
    advanced: true,
    group: "More Analytics",
  },
  {
    id: "settings",
    label: "Settings",
    href: "/analytics/settings",
    icon: Settings,
    description: "Analytics module settings",
    advanced: true,
    group: "More Analytics",
  },
];
