// @ts-nocheck
"use client";

import {
  Home,
  Package,
  TrendingUp,
  BarChart3,
  Truck,
  Car,
  FileText,
  DollarSign,
  Leaf,
  Layers,
  Brain,
  Users,
  Cpu,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui-layout";

export {
  ModuleTabLayout as SupplyChainTabLayout,
  type ModuleTab as SupplyChainTab,
  type ModuleTabLayoutProps as SupplyChainTabLayoutProps,
  SubTabBar,
  type SubTab,
} from "@unerp/ui-layout";

export const SUPPLY_CHAIN_TABS: ModuleTab[] = [
  {
    id: "overview",
    label: "Dashboard",
    href: "/supply-chain",
    icon: Home,
    description: "Supply chain overview",
  },
  {
    id: "control-tower",
    label: "Control Tower",
    href: "/supply-chain/control-tower",
    icon: Home,
    description: "End-to-end supply chain visibility and real-time monitoring",
  },
  {
    id: "operations",
    label: "Operations Hub",
    href: "/supply-chain/operations",
    icon: Package,
    description: "Supply chain operations",
  },
  {
    id: "demand-forecast",
    label: "Demand Forecast",
    href: "/supply-chain/demand-forecast",
    icon: TrendingUp,
    description: "Demand forecasting",
  },
  {
    id: "supply-planning",
    label: "Supply Planning",
    href: "/supply-chain/supply-planning",
    icon: TrendingUp,
    advanced: true,
    group: "Planning & Risk",
    description: "Capacity and inventory supply balance planning",
  },
  {
    id: "supplier-risk",
    label: "Supplier Risk",
    href: "/supply-chain/supplier-risk",
    icon: BarChart3,
    advanced: true,
    group: "Planning & Risk",
    description: "Vendor risk assessment and mitigation matrix",
  },
  {
    id: "global-trade",
    label: "Global Trade",
    href: "/supply-chain/global-trade",
    icon: Truck,
    advanced: true,
    group: "Logistics & Trade",
    description: "Cross-border compliance, tariffs, and customs clearances",
  },
  {
    id: "logistics",
    label: "Logistics",
    href: "/supply-chain/logistics",
    icon: Truck,
    advanced: true,
    group: "Logistics & Trade",
    description: "Freight execution, routing, and fleet logistics",
  },
  {
    id: "tracking",
    label: "Shipment Tracking",
    href: "/supply-chain/tracking",
    icon: Truck,
    description: "Live GPS and carrier milestone tracking",
  },
  {
    id: "shipments",
    label: "Shipments",
    href: "/supply-chain/shipments",
    icon: Truck,
    description: "Shipment tracking and carrier management",
  },
  {
    id: "carriers",
    label: "Carriers",
    href: "/supply-chain/carriers",
    icon: Truck,
    advanced: true,
    group: "Logistics & Trade",
    description: "Freight carrier directory and contract terms",
  },
  {
    id: "containers",
    label: "Containers",
    href: "/supply-chain/containers",
    icon: Package,
    advanced: true,
    group: "Logistics & Trade",
    description: "Container tracking and demurrage management",
  },
  {
    id: "customs",
    label: "Customs Declarations",
    href: "/supply-chain/customs",
    icon: Package,
    advanced: true,
    group: "Logistics & Trade",
    description: "Customs entry documents and duty tracking",
  },
  {
    id: "routes",
    label: "Shipping Routes",
    href: "/supply-chain/routes",
    icon: Truck,
    advanced: true,
    group: "Logistics & Trade",
    description: "Trade lane routes and transit time optimization",
  },
  {
    id: "lane-rates",
    label: "Lane Rates",
    href: "/supply-chain/lane-rates",
    icon: BarChart3,
    advanced: true,
    group: "Logistics & Trade",
    description: "Freight lane pricing and spot rate benchmarks",
  },
  {
    id: "contracts",
    label: "Logistics Contracts",
    href: "/supply-chain/contracts",
    icon: Package,
    advanced: true,
    group: "Logistics & Trade",
    description: "Carrier SLAs and freight service contracts",
  },
  {
    id: "supplier-performance",
    label: "Supplier Performance",
    href: "/supply-chain/supplier-performance",
    icon: BarChart3,
    advanced: true,
    group: "Suppliers",
    description: "OTIF metrics and vendor scorecards",
  },
  {
    id: "supplier-assessments",
    label: "Supplier Assessments",
    href: "/supply-chain/supplier-assessments",
    icon: BarChart3,
    advanced: true,
    group: "Suppliers",
    description: "Vendor audit checklists and ESG evaluations",
  },
  {
    id: "budgets",
    label: "Freight Budgets",
    href: "/supply-chain/budgets",
    icon: BarChart3,
    advanced: true,
    group: "Finance",
    description: "Transportation spend vs budget tracking",
  },
  {
    id: "analytics",
    label: "Analytics",
    href: "/supply-chain/analytics",
    icon: BarChart3,
    description: "Supply chain analytics",
  },
  {
    id: "settings",
    label: "Module Settings",
    href: "/supply-chain/settings",
    icon: BarChart3,
    advanced: true,
    group: "Settings",
    description: "Supply chain configuration and defaults",
  },
  {
    id: "fleet",
    label: "Fleet Management",
    href: "/supply-chain/fleet",
    icon: Car,
    advanced: true,
    group: "Logistics & Trade",
    description: "Vehicle tracking, maintenance, fuel logs, trip records",
  },
  {
    id: "carrier-contracts",
    label: "Carrier Contracts",
    href: "/supply-chain/carrier-contracts",
    icon: FileText,
    advanced: true,
    group: "Logistics & Trade",
    description: "Carrier contract negotiation, rate cards, spot quotes",
  },
  {
    id: "supply-chain-finance",
    label: "SC Finance",
    href: "/supply-chain/supply-chain-finance",
    icon: DollarSign,
    advanced: true,
    group: "Finance",
    description: "Invoice factoring, dynamic discounting, SCF programs",
  },
  {
    id: "sustainability",
    label: "Sustainability",
    href: "/supply-chain/sustainability",
    icon: Leaf,
    advanced: true,
    group: "Planning & Risk",
    description: "Carbon tracking, sustainability targets, ESG reporting",
  },
  {
    id: "meio",
    label: "MEIO",
    href: "/supply-chain/meio",
    icon: Layers,
    advanced: true,
    group: "Planning & Risk",
    description: "Multi-echelon inventory optimization and simulation",
  },
  {
    id: "advanced-analytics",
    label: "AI Analytics",
    href: "/supply-chain/advanced-analytics",
    icon: Brain,
    advanced: true,
    group: "Analytics",
    description: "ML demand sensing, anomaly detection, predictive lead times",
  },
  {
    id: "supplier-portal",
    label: "Supplier Portal",
    href: "/supply-chain/supplier-portal",
    icon: Users,
    advanced: true,
    group: "Suppliers",
    description: "Supplier onboarding, document exchange, PO collaboration",
  },
  {
    id: "digital-twin",
    label: "Digital Twin",
    href: "/supply-chain/digital-twin",
    icon: Cpu,
    advanced: true,
    group: "Control Tower",
    description:
      "Supply chain digital twin, what-if simulation, scenario comparison",
  },
];
