import {
  Home,
  CreditCard,
  Users,
  BarChart3,
  Package,
  ShoppingCart,
  ClipboardList,
  Truck,
  Briefcase,
  Hammer,
  PieChart,
  FolderOpen,
  MessageSquare,
  Store,
  GraduationCap,
  Building2,
  Wrench,
  Key,
  Cloud,
  ShieldAlert,
  ShoppingBag,
  Cpu,
  Sparkles,
  Workflow,
} from "lucide-react";
import { Globe as StorefrontIcon } from "lucide-react";
import type { AppDefinition, SwitcherFolder } from "./types";

export const SEGMENT_NAMES: Record<string, string> = {
  apps: "Apps",
  crm: "CRM",
  finance: "Finance",
  hr: "HR",
  inventory: "Inventory",
  procurement: "Procurement",
  projects: "Projects",
  programs: "Programs",
  agile: "Agile/Scrum",
  "resource-skills": "Resource Skills",
  "advanced-evm": "Advanced EVM",
  capex: "CAPEX",
  claims: "Claims & Changes",
  pmo: "PMO Dashboard",
  collaboration: "Collaboration",
  manufacturing: "Manufacturing",
  pos: "POS",
  communication: "Connect",
  connect: "Connect",
  drive: "Drive",
  analytics: "Analytics", // also used by workflow module
  settings: "Settings",
  profile: "Profile",
  builder: "Studio",
  build: "Build",
  erp: "App Studio",
  "advanced-forms": "Advanced Forms",
  bpmn: "BPMN",
  "api-builder": "API Builder",
  "rules-engine": "Rules Engine",
  "mobile-builder": "Mobile Apps",
  manage: "Manage",
  etl: "ETL & Data Transform",
  "theme-manager": "Themes",
  web: "Web Studio",
  "ab-testing": "A/B Testing",
  releases: "Releases",
  logs: "Run Logs",
  access: "Access Control",
  connectors: "Connectors",
  marketplace: "Marketplace",
  "query-builder": "Query Builder",
  widgets: "Widget SDK",
  git: "Git Control",
  "mobile-export": "Export & Mobile",
  collections: "CMS Collections",
  submissions: "Form Submissions",
  store: "App Store",
  "real-estate": "Real Estate",
  healthcare: "Healthcare",
  "healthcare-patients": "Patients",
  "healthcare-appointments": "Appointments",
  "healthcare-prescriptions": "Prescriptions",
  "healthcare-lab-orders": "Lab Orders",
  "healthcare-lab-results": "Lab Results",
  "healthcare-insurance": "Insurance",
  "healthcare-pharmacy": "Pharmacy",
  "healthcare-schedules": "Schedules",
  "healthcare-practitioners": "Practitioners",
  "healthcare-medical-records": "Medical Records",
  "healthcare-vitals": "Vitals",
  "healthcare-encounters": "Encounters",
  "healthcare-drugs": "Drugs",
  "healthcare-allergies": "Allergies",
  "healthcare-batches": "Batches",
  "healthcare-controlled-substances": "Controlled Substances",
  "healthcare-claims": "Claims",
  "healthcare-policies": "Policies",
  education: "Education",
  "education-students": "Students",
  "education-courses": "Courses",
  "education-enrollments": "Enrollments",
  "education-grades": "Grades",
  "education-gradebooks": "Gradebooks",
  "education-attendance": "Attendance",
  "education-fees": "Fees",
  "education-invoices": "Invoices",
  "education-payments": "Payments",
  "education-library": "Library",
  "education-fines": "Fines",
  "education-timetable": "Timetable",
  "education-exams": "Exams",
  "education-results": "Results",
  "education-parents": "Parents",
  "education-modules": "Course Modules",
  "education-books": "Books",
  "education-transactions": "Transactions",
  "field-service": "Field Service",
  portfolios: "Portfolios",
  buildings: "Buildings",
  units: "Units",
  payments: "Payments",
  vendors: "Vendors",
  "commission-plans": "Commission Plans",
  valuations: "Valuations",
  "market-analytics": "Market Analytics",
  expiring: "Expiring",
  renewals: "Renewals",
  slas: "SLAs",
  dispatch: "Dispatch",
  "mobile-dispatch": "Mobile Dispatch",
  "calendar-events": "Calendar Events",
  parts: "Parts & Inventory",
  "part-requests": "Part Requests",
  "van-stock": "Van Stock",
  "maintenance-requests": "Maintenance Requests",
  "lease-renewals": "Lease Renewals",
  "rent-escalations": "Rent Escalations",
  financials: "Property Financials",
  "property-financials": "Property Financials",
  "expense-categories": "Expense Categories",
  "portfolio-summary": "Portfolio Summary",
  appointments: "Appointments",
  "low-stock": "Low Stock",
  "parts-usage": "Parts Usage",
  contracts: "Contracts",
  timesheets: "Timesheets",
  schedule: "Schedule",
  saas: "SaaS",
  security: "Security",
  "org-hierarchy": "Org Hierarchy",
  delegations: "Delegations",
  "security-policies": "Security Policies",
  "compliance-governance": "Compliance & Governance",
  "approval-operations": "Approval Operations",
  "workflow-builder": "Workflow Builder",
  "branding-communication": "Branding & Communication",
  "system-operations": "System Operations",
  "general-branding": "General & Branding",
  "api-platform": "API Platform",
  "api-key-whitelists": "API Key Whitelists",
  "api-integration-hub": "API Integration Hub",
  "i18n-localization": "i18n Localization",
  "sync-monitor": "Sync Monitor",
  "devops-telemetry": "DevOps & Telemetry",
  "marketing-outreach": "Marketing & Outreach",
  automation: "Sales Automation",
  "customer-success": "Customer Success",
  "communication-deep": "Communication Deep",
  "sms-templates": "SMS Templates",
  "whatsapp-templates": "WhatsApp Templates",
  "social-posts": "Social Posts",
  "message-history": "Message History",
  "opt-out": "Opt-Out",
  "contract-deep": "Contract Deep",
  "clause-library": "Clause Library",
  obligations: "Obligations",
  compliance: "Compliance",
  "financial-summary": "Financial Summary",
  "value-at-risk": "Value at Risk",
  "version-history": "Version History",
  "expiry-calendar": "Expiry Calendar",
  journey: "Journey",
  stages: "Stages",
  nps: "NPS",
  surveys: "Surveys",
  churn: "Churn Predictions",
  clv: "CLV",
  upsell: "Upsell",
  "customer-360": "Customer 360",
  "sales-enablement": "Sales Enablement",
  content: "Content Library",
  categories: "Categories",
  "data-management": "Data Management",
  imports: "Imports",
  quality: "Data Quality",
  "bulk-operations": "Bulk Operations",
  duplicates: "Duplicates",
  export: "Export",
  "account-plans": "Account Plans",
  cpq: "CPQ Pricing",
  fulfillment: "Fulfillment",
  sla: "SLA Analytics",
  "operations-service": "Operations & Service",
  operations: "Operations",
  customers: "Customers",
  "customer-portal": "Customer Portal",
  contacts: "Contacts",
  cases: "Cases & SLA",
  leads: "Leads",
  opportunities: "Opportunities",
  quotations: "Quotations",
  reports: "Reports",
  "sales-orders": "Sales Orders",
  activities: "Activities",
  "email-templates": "Email Templates",
  advanced: "Advanced",
  segments: "Segments",
  "duplicate-rules": "Duplicate Rules",
  pipelines: "Pipelines",
  "sla-policies": "SLA Policies",
  "email-integration": "Email Integration",
  "purchase-orders": "Purchase Orders",
  "purchase-receipts": "Purchase Receipts",
  returns: "Returns",
  rfqs: "RFQs",
  "supplier-quotations": "Supplier Quotations",
  "delivery-notes": "Delivery Notes",
  orders: "Orders",
  search: "Search",
  "saved-views": "Saved Views",
  templates: "Templates",
  preferences: "Preferences",
  digests: "Digests",
  "client-portal": "Client Portal",
  health: "Strategic Health",
  workloads: "Workloads",
  "revenue-recognition": "Revenue Recognition",
  "wip-reports": "WIP & Job Costing",
  boms: "BOMs",
  configurator: "Configurator",
  diagnostics: "Diagnostics",
  "advanced-quality": "Advanced Quality",
  tooling: "Tooling & Gages",
  aps: "APS Scheduler",
  energy: "Energy Management",
  lean: "Lean Manufacturing",
  tpm: "TPM",
  "contract-mfg": "Contract Manufacturing",
  ddmrp: "DDMRP",
  mrp: "MRP",
  scheduling: "Scheduling",
  "shop-floor": "Shop Floor",
  designer: "Receipt Designer",
  "ap-automation": "AP Automation",
  "ar-automation": "AR Automation",
  "bank-accounts": "Bank Accounts",
  "bank-feeds": "Bank Connections",
  "bank-recon": "Bank Reconciliation",
  "cash-flow-forecast": "Cash Flow Forecast",
  intercompany: "Intercompany",
  netting: "Netting",
  eliminations: "Eliminations",
  "fx-revaluation": "FX Revaluation",
  "corporate-cards": "Corporate Cards",
  "1099-reporting": "1099 / Vendor Tax Reporting",
  "tax-nexus": "Economic Nexus Monitoring",
  "payment-terms": "Payment Terms",
  "invoice-analytics": "Invoice Analytics",
  "tax-filing-summary": "Tax Filing Summary",
  "ar-aging": "AR Aging Report",
  "customer-statement": "Customer Statement",
  "credit-risk": "Credit Risk Management",
  ai: "AI Copilot",
  "forecast-scenarios": "Rolling Forecasts (xP&A)",
  "accounting-books": "Accounting Books",
  budgeting: "Budgeting",
  "chart-of-accounts": "Chart of Accounts",
  "financial-periods": "Financial Periods",
  "fixed-assets": "Fixed Assets",
  "journal-entries": "Journal Entries",
  "tax-engine": "Tax Engine",
  "tax-filing": "Tax Filing",
  treasury: "Treasury",
  appraisals: "Appraisals",
  assets: "Assets",
  attendance: "Attendance",
  benefits: "Benefits",
  feedback: "Feedback",
  goals: "Goals",
  holidays: "Holidays",
  leaves: "Leaves",
  offboarding: "Offboarding",
  onboarding: "Onboarding",
  payroll: "Payroll",
  positions: "Positions",
  recruitment: "Recruitment",
  "self-service": "Self-Service",
  shifts: "Shifts",
  skills: "Skills",
  succession: "Succession",
  tickets: "Tickets",
  trainings: "Trainings",
  batches: "Batches",
  "bin-locations": "Bin Locations",
  "cycle-counts": "Cycle Counts",
  "cycle-count-schedules": "Cycle Count Schedules",
  "license-plates": "License Plates & Put-away",
  traceability: "Traceability",
  "stock-reservations": "Stock Reservations & Analytics",
  kits: "Kits & Assembly",
  "transfer-approvals": "Transfer Approvals",
  "movement-history": "Movement History & Labels",
  "pick-waves": "Wave Picking",
  "mobile-pick": "Mobile Scan Pick/Pack",
  consignment: "Consignment Inventory",
  "reorder-rules": "Reorder Rules & Automation",
  "qa-templates": "QA Templates & Routing",
  "expiry-fefo": "Expiry, FEFO & Recalls",
  "cross-dock": "Cross-Docking",
  slotting: "Slotting Optimization",
  "dock-scheduling": "Dock Scheduling",
  "demand-forecasting": "Demand Forecasting",
  "landed-cost": "Landed Cost",
  "stock-valuation": "Stock Valuation",
  "transfer-orders": "Transfer Orders",
  "yard-management": "Yard Management",
  "stock-takes": "Physical Inventory",
  hazmat: "Hazardous Materials",
  asl: "Approved Suppliers",
  "container-pallet": "Container & Pallet Management",
  "catch-weight-recall": "Catch-Weight & Product Recall",
  "packaging-gs1": "Packaging Specifications & GS1",
  "cold-chain-writeoff": "Cold Chain & Inventory Write-Off Management",
  "velocity-abc-xyz": "Inventory Velocity & ABC-XYZ Classification",
  "customer-returns": "Customer Returns & Reverse Logistics",
  "minmax-replen": "Min-Max Replenishment Planning",
  "freight-claims": "Freight Claims & Cargo Damage Reporting",
  vmi: "Vendor-Managed Inventory (VMI)",
  costing: "Inventory Costing Methods (FIFO/LIFO/WAC)",
  "lot-expiry": "Lot/Batch Expiry Management & FEFO",
  rtv: "Returns to Vendor (RTV)",
  "labor-management": "Labor Management",
  "supplier-quality": "Supplier Quality Management",
  "automation-rules": "Automation Rules",
  "inventory-analytics": "Inventory Analytics",
  logistics: "Logistics & Shipping",
  "quality-compliance": "Quality & Compliance",
  "warehouse-ops": "Warehouse Operations",
  "lot-serial": "Lot & Serial Tracking",
  "qa-inspections": "QA Inspections",
  "serial-numbers": "Serial Numbers",
  "stock-entries": "Stock Entries",
  "stock-ledger": "Stock Ledger",
  "stock-levels": "Stock Levels",
  warehouses: "Warehouses",
  escalations: "Escalations",
  simulation: "Simulation",
  requisitions: "Requisitions",
  "blanket-agreements": "Blanket Agreements",
  portal: "Supplier Portal",
  "super-admin": "Super Admin",
  "access-control": "Access Control",
  tenants: "Tenants",
  admins: "Admin Users",
  "activity-feed": "Activity Feed",
  announcements: "Announcements",
  "scheduled-reports": "Scheduled Reports",
  notifications: "Notifications",
  "import-export": "Import / Export",
  gdpr: "GDPR",
  workflows: "Workflows",
  quotas: "Storage Quotas",
  media: "Media Conversion",
  groups: "User Groups",
  mfa: "MFA Settings",
  "password-policy": "Password Policies",
  sessions: "Sessions",
  impersonate: "Impersonate User",
  "ip-restrictions": "IP Restrictions",
  "audit-trail": "Audit Trail",
  "login-history": "Login History",
  "data-retention": "Data Retention",
  "login-customizer": "Login Customizer",
  "email-config": "SMTP Server",
  maintenance: "Maintenance Mode", // also used by fixed-assets module
  "system-health": "System Health",
  jobs: "Background Jobs",
  "scheduled-tasks": "Scheduled Tasks",
  "error-logs": "Error Logs",
  backups: "Database Backups",
  "db-schema": "Database Schema",
  modules: "Module Manager",
  "feature-flags": "Feature Flags",
  domains: "Custom Domains",
  environments: "Environments",
  updates: "System Updates",
  "tenant-analytics": "Tenant Analytics",
  bulk: "Bulk Approvals",
  routing: "Dynamic Routing",
  email: "Email Approvals",
  general: "General Settings",
  branding: "Branding & Appearance",
  integrations: "Integrations",
  import: "Import Data",
  erasure: "GDPR Erasure",
  retention: "GDPR Retention",
  webhooks: "Webhooks Configuration", // also used by api-platform module
  "webhook-logs": "Webhook Logs",
  oauth: "SSO & OAuth",
  sandbox: "Developer Sandbox",
  roles: "User Roles",
  packages: "Access Packages",
  matrix: "Permissions Matrix",
  "identity-access": "Identity & Access",
  // Storage module
  storage: "Storage",
  "file-browser": "File Browser",
  shared: "Shared Files",
  quota: "Storage Quota",
  versions: "File Versions",
  // Workflow module
  workflow: "Workflow",
  definitions: "Definitions",
  instances: "Instances",
  tasks: "My Tasks",
  "sla-rules": "SLA Rules",
  "audit-log": "Audit Log",
  // Fixed Assets sub-pages
  depreciation: "Depreciation",
  disposals: "Disposals",
  // API Platform module
  "api-keys": "API Keys",
  "usage-dashboard": "Usage Dashboard",
  "endpoint-registry": "Endpoint Registry",
  // Localization module
  localization: "Localization",
  locales: "Locales",
  translations: "Translations",
  "translation-editor": "Translation Editor",
  // Supply Chain route segments
  "control-tower": "Control Tower",
  "supply-planning": "Supply Planning",
  "supplier-risk": "Supplier Risk",
  "global-trade": "Global Trade",
  tracking: "Tracking",
  carriers: "Carriers",
  containers: "Container Tracking",
  customs: "Customs",
  routes: "Routes",
  "lane-rates": "Lane Rates",
  "supplier-performance": "Supplier Performance",
  "supplier-assessments": "Supplier Assessments",
  budgets: "Budgets",
  ecommerce: "E-Commerce",
  listings: "Listings",
  intelligence: "Intelligence",
  "lead-scoring": "Lead Scoring",
  "deal-velocity": "Deal Velocity",
  partners: "Partner Management",
  sentiment: "Sentiment & Health",
  campaigns: "Campaign Analytics",
  // Finance Payables & AP matching
  "ap-match-rules": "AP Match Rules",
  "exception-queue": "AP Exception Queue",
  "payment-batches": "Payment Batches",
  "invoice-capture": "AI Invoice Capture",
  payables: "Payables",
  // Finance Subscriptions & Leases
  subscriptions: "Subscription Billing",
  leases: "Lease Accounting",
  new: "New",
  allocations: "Dynamic Allocations",
  // Finance FP&A / Close
  "close-tasks": "Close Checklist",
  "budget-scenarios": "Budget Scenarios",
  "scenario-comparison": "Scenario Comparison",
  // Finance Tab-based module pages
  gl: "General Ledger",
  ar: "Accounts Receivable",
  ap: "Accounts Payable",
  banking: "Banking",
  "budget-planning": "Budget & Planning",
  // CRM Sales Ops Automation (territory rules, cadences, e-signature certs)
  territories: "Territories",
  "assignment-rules": "Assignment Rules",
  sequences: "Sequences",
  cadences: "Sales Cadences",
  "auto-enroll": "Auto-Enroll Rules",
  signatures: "E-Signatures",
  "pipeline-risk": "Pipeline Risk Alerts",
  forecasting: "Forecasting",
  "revenue-intelligence": "Revenue Intelligence",
  "conversation-intelligence": "Conversation Intelligence",
  "conversion-analytics": "Conversion Analytics",
  "ai-drafting": "AI Drafting",
  gamification: "Gamification & Leaderboards",
  // also used by real-estate module
  coaching: "Sales Coaching",
  "deal-rooms": "Deal Rooms",
  "account-hierarchy": "Account Hierarchy",
  // DevOps Pipeline
  devops: "DevOps",
  deployments: "Deployments",
  "deployment-analytics": "Deployment Analytics",
  "build-logs": "Build Logs",
  // PWA
  pwa: "PWA",
  "cache-rules": "Cache Rules",
  "push-subscriptions": "Push Subscriptions",
  "install-prompt": "Install Prompt",
  "service-worker": "Service Worker",
  "sync-queue": "Sync Queue",
  // Outbox
  outbox: "Outbox",
  dlq: "Dead Letter Queue",
  "dead-letters": "Dead Letters",
  "outbox-analytics": "Outbox Analytics",
  dispatcher: "Dispatcher",
  "retry-logs": "Retry Logs",
  // Extension Gateway
  "ext-gateway": "Extension Gateway",
  connections: "Connections",
  "ext-webhooks": "Webhooks",
  "rate-limits": "Rate Limits",
  "integration-templates": "Templates",
  "ext-analytics": "Analytics",
  // T4 Finance-Adjacent modules
  reporting: "Reporting",
  "subscription-plans": "Plans",
  "subscription-tiers": "Tiers",
  "subscription-coupons": "Coupons",
  "subscription-usage": "Usage",
  "subscription-dunning": "Dunning",
  "subscription-credit-notes": "Credit Notes",
  "subscription-migrations": "Migrations",
  "localization-locales": "Locales",
  "localization-translations": "Translations",
  "localization-glossary": "Glossary",
  "localization-regions": "Regions",
  "localization-machine-translation": "Machine Translation",
  "localization-content-schedule": "Content Schedule",
  "localization-fallback": "Fallback",
  "fixed-assets-categories": "Categories",
  "fixed-assets-maintenance": "Maintenance",
  "fixed-assets-insurance": "Insurance",
  "fixed-assets-groups": "Groups",
  "fixed-assets-audits": "Audits",
  "fixed-assets-transfers": "Transfers",
  "reporting-templates": "Templates",
  "reporting-exports": "Exports",
  "reporting-bookmarks": "Bookmarks",
  "reporting-alerts": "Alerts",
  "reporting-viewer": "Viewer",
  "reporting-drilldown": "Drilldown",
  "reporting-compliance": "Compliance",
};

export const formatSegment = (segment: string): string => {
  const name = SEGMENT_NAMES[segment.toLowerCase()];
  if (name) {
    return name;
  }
  return segment
    .split(/[-_]/)
    .map((word: any) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

import { Activity, ShieldCheck } from "lucide-react";

/**
 * Every top-level operational business application known to the shell.
 * Migrated modules (Marketplace -> :4007, Studio/Ecommerce -> :4005, SaaS Portal -> :4006)
 * live in their dedicated repositories and are not listed here.
 */
export const allApplications: AppDefinition[] = [
  {
    id: "analytics",
    name: "Analytics & Cockpit",
    href: "/analytics",
    icon: PieChart,
    installed: true,
  },
  {
    id: "finance",
    name: "Finance & Accounting",
    href: "/finance",
    icon: CreditCard,
    installed: true,
  },
  {
    id: "hr",
    name: "Human Resources",
    href: "/hr",
    icon: Users,
    installed: true,
  },
  {
    id: "crm",
    name: "CRM & Sales",
    href: "/crm",
    icon: BarChart3,
    installed: true,
  },
  {
    id: "inventory",
    name: "Inventory & Stock",
    href: "/inventory",
    icon: Package,
    installed: true,
  },
  {
    id: "procurement",
    name: "Procurement",
    href: "/procurement",
    icon: ShoppingCart,
    installed: true,
  },
  {
    id: "sales",
    name: "Sales & Orders",
    href: "/sales",
    icon: ClipboardList,
    installed: true,
  },
  {
    id: "supply-chain",
    name: "Supply Chain",
    href: "/supply-chain",
    icon: Truck,
    installed: true,
  },
  {
    id: "projects",
    name: "Project Management",
    href: "/projects",
    icon: Briefcase,
    installed: true,
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    href: "/manufacturing",
    icon: Hammer,
    installed: true,
  },
  {
    id: "workflow",
    name: "Workflow Automation",
    href: "/workflow",
    icon: Workflow,
    installed: true,
  },
  {
    id: "ai",
    name: "AI Copilot",
    href: "/ai",
    icon: Sparkles,
    installed: true,
  },
  {
    id: "drive",
    name: "Drive",
    href: "/drive",
    icon: FolderOpen,
    installed: true,
  },
  {
    id: "communication",
    name: "Connect",
    href: "/connect",
    icon: MessageSquare,
    installed: true,
  },
  {
    id: "pos",
    name: "POS & Retail",
    href: "/pos",
    icon: Store,
    installed: true,
  },
  {
    id: "healthcare",
    name: "Healthcare",
    href: "/healthcare",
    icon: Activity,
    installed: true,
  },
  {
    id: "education",
    name: "Education",
    href: "/education",
    icon: GraduationCap,
    installed: true,
  },
  {
    id: "real-estate",
    name: "Real Estate",
    href: "/real-estate",
    icon: Building2,
    installed: true,
  },
  {
    id: "field-service",
    name: "Field Service",
    href: "/field-service",
    icon: Wrench,
    installed: true,
  },
  {
    id: "blockchain",
    name: "Blockchain Ledger",
    href: "/blockchain",
    icon: ShieldCheck,
    installed: true,
  },
];

export const switcherFolders: SwitcherFolder[] = [];

/**
 * Kernel app identifiers that are permanently accessible without conditional gating.
 */
export const KERNEL_APP_IDS = new Set([
  "dashboard",
  "finance",
  "hr",
  "crm",
  "inventory",
  "procurement",
  "sales",
  "supply-chain",
  "projects",
  "manufacturing",
  "analytics",
  "ai",
  "drive",
  "communication",
  "pos",
  "healthcare",
  "education",
  "real-estate",
  "field-service",
  "blockchain",
  "workflow",
]);
