"use client";

import { useEffect, useRef } from "react";

export {
  ModuleTabLayout as CrmTabLayout,
  type ModuleTab as CrmTab,
  type ModuleTabLayoutProps as CrmTabLayoutProps,
} from "@unerp/ui-layout";

import {
  BarChart3,
  UserPlus,
  Target,
  Building2,
  Users,
  PieChart,
  Activity,
  Handshake,
  Settings,
  Package,
  Zap,
  HelpCircle,
  BookOpen,
  MapPin,
  Brain,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui-layout";

export const CRM_TABS: ModuleTab[] = [
  {
    id: "overview",
    label: "Dashboard",
    href: "/crm",
    icon: BarChart3,
    description: "CRM executive dashboard",
  },
  {
    id: "leads",
    label: "Leads",
    href: "/crm/leads",
    icon: UserPlus,
    description: "Lead management and qualification",
  },
  {
    id: "opportunities",
    label: "Opportunities",
    href: "/crm/opportunities",
    icon: Target,
    description: "Sales pipeline and deal tracking",
  },
  {
    id: "customers",
    label: "Customers",
    href: "/crm/customers",
    icon: Building2,
    description: "Customer accounts directory",
  },
  {
    id: "contacts",
    label: "Contacts",
    href: "/crm/contacts",
    icon: Users,
    description: "Contact directory and relationships",
  },
  {
    id: "marketing",
    label: "Marketing",
    href: "/crm/marketing-outreach",
    icon: PieChart,
    description: "Campaigns and marketing outreach",
    advanced: true,
    group: "Advanced",
  },
  {
    id: "automation",
    label: "Automation",
    href: "/crm/automation",
    icon: Activity,
    description: "Sales automation and sequences",
    advanced: true,
    group: "Advanced",
  },
  {
    id: "customer-success",
    label: "Customer Success",
    href: "/crm/customer-success",
    icon: Handshake,
    description: "Customer health and retention",
    advanced: true,
    group: "Advanced",
  },
  {
    id: "settings",
    label: "Settings",
    href: "/crm/settings",
    icon: Settings,
    description: "CRM module settings",
    advanced: true,
    group: "Settings",
  },

  // ---- Account Management ----
  {
    id: "vendors",
    label: "Vendors",
    href: "/crm/vendors",
    icon: Building2,
    advanced: true,
    group: "Account Management",
    description: "Vendor directory and relationships",
  },
  {
    id: "contracts",
    label: "Contracts",
    href: "/crm/contracts",
    icon: Building2,
    advanced: true,
    group: "Account Management",
    description: "Customer and vendor contracts",
  },
  {
    id: "customer-portal",
    label: "Customer Portal",
    href: "/crm/customer-portal",
    icon: Building2,
    advanced: true,
    group: "Account Management",
    description: "Self-service customer portal configuration",
  },

  // ---- Sales Pipeline ----
  {
    id: "sales-products",
    label: "Products",
    href: "/crm/products",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Sellable product catalog",
  },
  {
    id: "price-books",
    label: "Price Books",
    href: "/crm/price-books",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Price books and list pricing",
  },
  {
    id: "quotations",
    label: "Quotations",
    href: "/crm/quotations",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Sales quotations",
  },
  {
    id: "quotation-signatures",
    label: "E-Signatures",
    href: "/crm/quotations/signatures",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Electronic signature tracking for quotations",
  },
  {
    id: "sales-orders",
    label: "Sales Orders",
    href: "/crm/sales-orders",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Confirmed sales orders",
  },
  {
    id: "pipeline-risk",
    label: "Pipeline Risk Alerts",
    href: "/crm/forecasting/pipeline-risk",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "At-risk deal alerts",
  },
  {
    id: "revenue-intelligence",
    label: "Revenue Intelligence",
    href: "/crm/forecasting/revenue-intelligence",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Revenue intelligence analytics",
  },
  {
    id: "conversation-intelligence",
    label: "Conversation Intelligence",
    href: "/crm/conversation-intelligence",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Call and conversation analytics",
  },
  {
    id: "conversion-analytics",
    label: "Conversion Analytics",
    href: "/crm/forecasting/conversion-analytics",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Lead-to-deal conversion analytics",
  },
  {
    id: "ai-drafting",
    label: "AI Drafting",
    href: "/crm/ai-drafting",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "AI-assisted email and proposal drafting",
  },
  {
    id: "sales-coaching",
    label: "Sales Coaching",
    href: "/crm/coaching",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Rep coaching and call scoring",
  },
  {
    id: "deal-rooms",
    label: "Deal Rooms",
    href: "/crm/deal-rooms",
    icon: Package,
    advanced: true,
    group: "Sales Pipeline",
    description: "Shared deal rooms for buyer collaboration",
  },

  // ---- Automation & Workflows ----
  {
    id: "workflow-rules",
    label: "Workflow Rules",
    href: "/crm/workflows",
    icon: Zap,
    advanced: true,
    group: "Automation & Workflows",
    description: "Automated workflow rule builder",
  },
  {
    id: "approvals",
    label: "Approvals",
    href: "/crm/approvals",
    icon: Zap,
    advanced: true,
    group: "Automation & Workflows",
    description: "Approval requests and history",
  },
  {
    id: "activities",
    label: "Activities",
    href: "/crm/activities",
    icon: Zap,
    advanced: true,
    group: "Automation & Workflows",
    description: "Tasks, calls, and logged activities",
  },
  {
    id: "documents",
    label: "Documents",
    href: "/crm/documents",
    icon: Zap,
    advanced: true,
    group: "Automation & Workflows",
    description: "Document library and templates",
  },

  // ---- Customer Service ----
  {
    id: "cases",
    label: "Cases & SLA",
    href: "/crm/cases",
    icon: HelpCircle,
    advanced: true,
    group: "Customer Service",
    description: "Support case tracking",
  },
  {
    id: "cases-sla",
    label: "SLA Dashboard",
    href: "/crm/cases/sla",
    icon: HelpCircle,
    advanced: true,
    group: "Customer Service",
    description: "SLA compliance dashboard",
  },

  // ---- Sales Enablement ----
  {
    id: "sales-enablement",
    label: "Sales Enablement Hub",
    href: "/crm/sales-enablement",
    icon: BookOpen,
    advanced: true,
    group: "Sales Enablement",
    description: "Playbooks, content, and enablement resources",
  },
  {
    id: "segments",
    label: "Segments",
    href: "/crm/segments",
    icon: BookOpen,
    advanced: true,
    group: "Sales Enablement",
    description: "Customer and lead segmentation",
  },
  {
    id: "knowledge-base",
    label: "Knowledge Base",
    href: "/crm/knowledge-base",
    icon: BookOpen,
    advanced: true,
    group: "Sales Enablement",
    description: "Internal knowledge base articles",
  },

  // ---- Teams & Territories ----
  {
    id: "territories",
    label: "Territories",
    href: "/crm/territories",
    icon: MapPin,
    advanced: true,
    group: "Teams & Territories",
    description: "Sales territory definitions",
  },
  {
    id: "assignment-rules",
    label: "Assignment Rules",
    href: "/crm/territories/assignment-rules",
    icon: MapPin,
    advanced: true,
    group: "Teams & Territories",
    description: "Lead and account assignment rules",
  },
  {
    id: "commissions",
    label: "Commissions",
    href: "/crm/commissions",
    icon: MapPin,
    advanced: true,
    group: "Teams & Territories",
    description: "Rep commission tracking",
  },
  {
    id: "commission-plans",
    label: "Commission Plans",
    href: "/crm/commission-plans",
    icon: MapPin,
    advanced: true,
    group: "Teams & Territories",
    description: "Commission plan configuration",
  },
  {
    id: "sales-cadences",
    label: "Sales Cadences",
    href: "/crm/sequences/cadences",
    icon: MapPin,
    advanced: true,
    group: "Teams & Territories",
    description: "Outreach sequence cadences",
  },
  {
    id: "gamification",
    label: "Gamification & Leaderboards",
    href: "/crm/gamification",
    icon: MapPin,
    advanced: true,
    group: "Teams & Territories",
    description: "Sales leaderboards and gamification",
  },

  // ---- Analytics & Reports ----
  {
    id: "forecasting",
    label: "Forecasting",
    href: "/crm/forecasting",
    icon: PieChart,
    advanced: true,
    group: "Analytics & Reports",
    description: "Sales forecasting",
  },
  {
    id: "account-plans",
    label: "Account Plans",
    href: "/crm/account-plans",
    icon: PieChart,
    advanced: true,
    group: "Analytics & Reports",
    description: "Strategic account plans",
  },
  {
    id: "account-hierarchy",
    label: "Account Hierarchy",
    href: "/crm/account-hierarchy",
    icon: PieChart,
    advanced: true,
    group: "Analytics & Reports",
    description: "Parent/child account hierarchy",
  },
  {
    id: "crm-reports",
    label: "Reports",
    href: "/crm/reports",
    icon: PieChart,
    advanced: true,
    group: "Analytics & Reports",
    description: "CRM reporting",
  },
  {
    id: "win-loss",
    label: "Win/Loss Analysis",
    href: "/crm/win-loss",
    icon: PieChart,
    advanced: true,
    group: "Analytics & Reports",
    description: "Win/loss deal analysis",
  },
  {
    id: "crm-dashboards",
    label: "Dashboards",
    href: "/crm/dashboards",
    icon: PieChart,
    advanced: true,
    group: "Analytics & Reports",
    description: "Custom CRM dashboards",
  },
  {
    id: "crm-advanced",
    label: "Advanced",
    href: "/crm/advanced",
    icon: PieChart,
    advanced: true,
    group: "Analytics & Reports",
    description: "Advanced CRM configuration hub",
  },

  // ---- CRM Intelligence & AI ----
  {
    id: "intelligence-hub",
    label: "Intelligence Hub",
    href: "/crm/intelligence",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "AI-powered CRM intelligence hub",
  },
  {
    id: "lead-scoring-intel",
    label: "Predictive Lead Scoring",
    href: "/crm/intelligence/lead-scoring",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Predictive lead scoring models",
  },
  {
    id: "customer-health",
    label: "Customer Health & Churn",
    href: "/crm/intelligence/health",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Customer health and churn risk",
  },
  {
    id: "deal-velocity",
    label: "Deal Velocity",
    href: "/crm/intelligence/deal-velocity",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Deal velocity analytics",
  },
  {
    id: "attribution-journey",
    label: "Attribution & Journey",
    href: "/crm/intelligence/journey",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Marketing attribution and customer journey",
  },
  {
    id: "sentiment-health",
    label: "Sentiment & Health",
    href: "/crm/intelligence/sentiment",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Sentiment analysis and account health",
  },
  {
    id: "clv-analytics",
    label: "CLV Analytics",
    href: "/crm/intelligence/clv",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Customer lifetime value analytics",
  },
  {
    id: "partner-management-intel",
    label: "Partner Management",
    href: "/crm/intelligence/partners",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Partner performance intelligence",
  },
  {
    id: "partner-deal-registration",
    label: "Partner Deal Registration",
    href: "/crm/partner-management",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Partner deal registration workflow",
  },
  {
    id: "campaign-analytics",
    label: "Campaign Analytics",
    href: "/crm/intelligence/campaigns",
    icon: Brain,
    advanced: true,
    group: "CRM Intelligence & AI",
    description: "Marketing campaign performance analytics",
  },

  // ---- Settings (detail pages) ----
  {
    id: "settings-custom-fields",
    label: "Custom Fields",
    href: "/crm/settings/custom-fields",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Custom field definitions",
  },
  {
    id: "settings-record-types",
    label: "Record Types",
    href: "/crm/settings/record-types",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Record type configuration",
  },
  {
    id: "settings-approvals",
    label: "Approval Processes",
    href: "/crm/settings/approvals",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Approval process configuration",
  },
  {
    id: "settings-lead-scoring",
    label: "Lead Scoring",
    href: "/crm/settings/lead-scoring",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Lead scoring rule configuration",
  },
  {
    id: "settings-duplicate-rules",
    label: "Duplicate Rules",
    href: "/crm/settings/duplicate-rules",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Duplicate detection rules",
  },
  {
    id: "settings-pipelines",
    label: "Pipelines",
    href: "/crm/settings/pipelines",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Sales pipeline stage configuration",
  },
  {
    id: "settings-sla-policies",
    label: "SLA Policies",
    href: "/crm/settings/sla-policies",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "SLA policy configuration",
  },
  {
    id: "settings-email-integration",
    label: "Email Integration",
    href: "/crm/settings/email-integration",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Email integration configuration",
  },
  {
    id: "communication-templates",
    label: "Communication Templates",
    href: "/crm/communication-templates",
    icon: Settings,
    advanced: true,
    group: "Settings",
    description: "Reusable communication templates",
  },
];

const OLD_PREFIXES = [
  ["unerp:crm:pins", "unerp:tabs:pins"],
  ["unerp:crm:recent", "unerp:tabs:recent"],
  ["unerp:tab_order_crm", "unerp:tabs:order"],
] as const;

let migrated = false;

export function useCrmKeyMigration() {
  const ran = useRef(false);
  useEffect(() => {
    if (migrated || ran.current || typeof window === "undefined") return;
    ran.current = true;
    migrated = true;
    for (const [oldPrefix, newPrefix] of OLD_PREFIXES) {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && key.startsWith(oldPrefix)) {
          const suffix = key.slice(oldPrefix.length);
          const newKey = `${newPrefix}${suffix}`;
          if (!localStorage.getItem(newKey)) {
            localStorage.setItem(newKey, localStorage.getItem(key)!);
          }
        }
      }
    }
  }, []);
}
