"use client";

/**
 * Thin re-export following the Finance/CRM tab-layout convention
 * (see apps/web/src/components/finance/FinanceTabLayout.tsx and
 * apps/web/src/components/crm/CrmTabLayout.tsx). The canonical
 * implementation lives in @unerp/ui-layout as ModuleTabLayout.
 *
 * SETTINGS_TABS enumerates every page under
 * apps/web/app/(dashboard)/settings/** so the module is fully
 * navigable without falling back to the sidebar (HANDBOOK §8.3).
 * The nine hub pages (Identity & Access, Security, Branding &
 * Communication, General & Branding, Workflow Builder, Approval
 * Operations, API Platform, Import / Export, System Operations) are
 * primary tabs; each hub's own second-level sections are handled by
 * SubTabBar inside that page. The remaining ~70 flat, single-view
 * pages are reachable as `advanced` tabs grouped under the "Advanced"
 * dropdown so every route stays addressable from the tab bar.
 */

import {
  Users,
  ShieldCheck,
  Lock,
  Image as ImageIcon,
  Settings,
  Workflow,
  CheckCircle,
  Zap,
  Import,
  Server,
  LayoutGrid,
  KeyRound,
  Grid3x3,
  UserCog,
  ScrollText,
  Fingerprint,
  History,
  ShieldAlert,
  FileWarning,
  Trash2,
  Database,
  ScanEye,
  CalendarClock,
  Palette,
  Smartphone,
  Flame,
  Settings2,
  Mail,
  Megaphone,
  MailWarning,
  Cpu,
  Globe2,
  ActivitySquare,
  Layers,
  CalendarDays,
  AlertCircle,
  Bell,
  RefreshCw,
  ListChecks,
  Repeat,
  Plug,
  Webhook,
  ExternalLink,
  BarChart3,
  Box,
  Activity,
  Globe,
  Building2,
  HeartPulse,
  ServerCog,
  Upload,
  Download,
  GitFork,
  CheckSquare,
  ShieldQuestion,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui-layout";

export {
  ModuleTabLayout as SettingsTabLayout,
  type ModuleTab as SettingsTab,
  type ModuleTabLayoutProps as SettingsTabLayoutProps,
} from "@unerp/ui-layout";

export const SETTINGS_TABS: ModuleTab[] = [
  {
    id: "overview",
    label: "Overview",
    href: "/settings",
    icon: LayoutGrid,
    description: "Administration dashboard — KPIs, activity, and quick links",
  },

  // --- Primary hub pages -------------------------------------------------
  {
    id: "identity-access",
    label: "Identity & Access",
    href: "/settings/identity-access",
    icon: Users,
    description: "Users, groups, roles, and access packages",
  },
  {
    id: "security",
    label: "Security",
    href: "/settings/security",
    icon: ShieldCheck,
    description: "SSO, MFA, sessions, audit trail, and access policies",
  },
  {
    id: "branding-communication",
    label: "Branding & Communication",
    href: "/settings/branding-communication",
    icon: ImageIcon,
    description: "Login page, SMTP, email templates, and announcements",
  },
  {
    id: "general-branding",
    label: "General & Branding",
    href: "/settings/general-branding",
    icon: Settings,
    description:
      "Organization profile, white-label, feature flags, custom fields",
  },
  {
    id: "approval-operations",
    label: "Approval Operations",
    href: "/settings/approval-operations",
    icon: CheckCircle,
    description: "Active approvals, bulk actions, analytics, and escalations",
  },
  {
    id: "workflow-builder",
    label: "Workflow Builder",
    href: "/settings/workflow-builder",
    icon: Workflow,
    description:
      "Approval templates, dynamic routing, email actions, simulator",
  },
  {
    id: "api-platform",
    label: "API Platform",
    href: "/settings/api-platform",
    icon: Zap,
    description: "API keys, OAuth clients, sandboxes, and webhooks",
  },
  {
    id: "import-export",
    label: "Import / Export",
    href: "/settings/import-export",
    icon: Import,
    description: "Bulk data import/export and offline sync monitor",
  },
  {
    id: "system-operations",
    label: "System Operations",
    href: "/settings/system-operations",
    icon: Server,
    description: "Health, background jobs, scheduled tasks, error logs, alerts",
  },

  // --- Security Details (advanced) ---------------------------------------
  {
    id: "access-control",
    label: "Access Control",
    href: "/settings/access-control",
    icon: KeyRound,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "access-control-matrix",
    label: "Permission Matrix",
    href: "/settings/access-control/matrix",
    icon: Grid3x3,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "access-control-roles",
    label: "Roles",
    href: "/settings/access-control/roles",
    icon: UserCog,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "access-control-packages",
    label: "Access Packages",
    href: "/settings/access-control/packages",
    icon: Box,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "users",
    label: "Users",
    href: "/settings/users",
    icon: Users,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "groups",
    label: "Groups & Teams",
    href: "/settings/groups",
    icon: Users,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "sso",
    label: "SSO",
    href: "/settings/sso",
    icon: Fingerprint,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "mfa",
    label: "MFA",
    href: "/settings/mfa",
    icon: ShieldQuestion,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "password-policy",
    label: "Password Policy",
    href: "/settings/password-policy",
    icon: Lock,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "ip-restrictions",
    label: "IP Restrictions",
    href: "/settings/ip-restrictions",
    icon: ShieldAlert,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "sessions",
    label: "Sessions",
    href: "/settings/sessions",
    icon: ScanEye,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "login-history",
    label: "Login History",
    href: "/settings/login-history",
    icon: History,
    advanced: true,
    group: "Security Details",
  },
  {
    id: "audit-trail",
    label: "Audit Trail",
    href: "/settings/audit-trail",
    icon: ScrollText,
    advanced: true,
    group: "Security Details",
  },

  // --- Compliance & Data (advanced) ---------------------------------------
  {
    id: "compliance",
    label: "Compliance",
    href: "/settings/compliance",
    icon: FileWarning,
    advanced: true,
    group: "Compliance & Data",
  },
  {
    id: "data-quality",
    label: "Data Quality",
    href: "/settings/data-quality",
    icon: Database,
    advanced: true,
    group: "Compliance & Data",
  },
  {
    id: "data-retention",
    label: "Data Retention",
    href: "/settings/data-retention",
    icon: CalendarClock,
    advanced: true,
    group: "Compliance & Data",
  },
  {
    id: "gdpr",
    label: "GDPR",
    href: "/settings/gdpr",
    icon: ShieldCheck,
    advanced: true,
    group: "Compliance & Data",
  },
  {
    id: "gdpr-erasure",
    label: "GDPR Erasure Requests",
    href: "/settings/gdpr/erasure",
    icon: Trash2,
    advanced: true,
    group: "Compliance & Data",
  },
  {
    id: "gdpr-retention",
    label: "GDPR Retention Rules",
    href: "/settings/gdpr/retention",
    icon: CalendarClock,
    advanced: true,
    group: "Compliance & Data",
  },
  {
    id: "backups",
    label: "Backups",
    href: "/settings/backups",
    icon: Database,
    advanced: true,
    group: "Compliance & Data",
  },
  {
    id: "recycle-bin",
    label: "Recycle Bin",
    href: "/settings/recycle-bin",
    icon: Trash2,
    advanced: true,
    group: "Compliance & Data",
  },
  {
    id: "db-schema",
    label: "DB Schema",
    href: "/settings/db-schema",
    icon: Database,
    advanced: true,
    group: "Compliance & Data",
  },

  // --- Branding Details (advanced) ----------------------------------------
  {
    id: "branding",
    label: "Branding",
    href: "/settings/branding",
    icon: Palette,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "white-label",
    label: "White-Label & PWA",
    href: "/settings/white-label",
    icon: Smartphone,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "feature-flags",
    label: "Feature Flags",
    href: "/settings/feature-flags",
    icon: Flame,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "custom-fields",
    label: "Custom Fields",
    href: "/settings/custom-fields",
    icon: Settings2,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "general",
    label: "General Settings",
    href: "/settings/general",
    icon: Settings,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "email-config",
    label: "Email Server (SMTP)",
    href: "/settings/email-config",
    icon: Mail,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "email-templates",
    label: "Email Templates",
    href: "/settings/email-templates",
    icon: Mail,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "announcements",
    label: "Announcements",
    href: "/settings/announcements",
    icon: Megaphone,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "maintenance",
    label: "Maintenance Mode",
    href: "/settings/maintenance",
    icon: MailWarning,
    advanced: true,
    group: "Branding Details",
  },
  {
    id: "login-customizer",
    label: "Login Customizer",
    href: "/settings/login-customizer",
    icon: ImageIcon,
    advanced: true,
    group: "Branding Details",
  },

  // --- System & DevOps (advanced) -----------------------------------------
  {
    id: "devops",
    label: "DevOps",
    href: "/settings/devops",
    icon: Cpu,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "environments",
    label: "Environments",
    href: "/settings/environments",
    icon: ServerCog,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "domains",
    label: "Domains",
    href: "/settings/domains",
    icon: Globe2,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "system-health",
    label: "System Health",
    href: "/settings/system-health",
    icon: HeartPulse,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "jobs",
    label: "Background Jobs",
    href: "/settings/jobs",
    icon: Layers,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "scheduled-tasks",
    label: "Scheduled Tasks",
    href: "/settings/scheduled-tasks",
    icon: CalendarDays,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "scheduled-reports",
    label: "Scheduled Reports",
    href: "/settings/scheduled-reports",
    icon: CalendarDays,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "error-logs",
    label: "Error Logs",
    href: "/settings/error-logs",
    icon: AlertCircle,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "alerts",
    label: "Admin Alerts",
    href: "/settings/alerts",
    icon: Bell,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "notifications",
    label: "Notifications",
    href: "/settings/notifications",
    icon: Bell,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "updates",
    label: "Updates",
    href: "/settings/updates",
    icon: RefreshCw,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "sync",
    label: "Sync Monitor",
    href: "/settings/sync",
    icon: Repeat,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "bulk-operations",
    label: "Bulk Operations",
    href: "/settings/bulk-operations",
    icon: ListChecks,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "automation-rules",
    label: "Automation Rules",
    href: "/settings/automation-rules",
    icon: Workflow,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "integrations",
    label: "Integrations",
    href: "/settings/integrations",
    icon: Plug,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "webhooks",
    label: "Webhooks",
    href: "/settings/webhooks",
    icon: Webhook,
    advanced: true,
    group: "System & DevOps",
  },
  {
    id: "webhook-logs",
    label: "Webhook Logs",
    href: "/settings/webhook-logs",
    icon: ExternalLink,
    advanced: true,
    group: "System & DevOps",
  },

  // --- API Platform Details (advanced) -------------------------------------
  {
    id: "api-keys",
    label: "API Keys",
    href: "/settings/api-keys",
    icon: KeyRound,
    advanced: true,
    group: "API Platform Details",
  },
  {
    id: "api-platform-analytics",
    label: "API Metrics & Analytics",
    href: "/settings/api-platform/analytics",
    icon: BarChart3,
    advanced: true,
    group: "API Platform Details",
  },
  {
    id: "api-platform-oauth",
    label: "OAuth Clients",
    href: "/settings/api-platform/oauth",
    icon: ShieldCheck,
    advanced: true,
    group: "API Platform Details",
  },
  {
    id: "api-platform-sandbox",
    label: "Developer Sandboxes",
    href: "/settings/api-platform/sandbox",
    icon: Box,
    advanced: true,
    group: "API Platform Details",
  },

  // --- Analytics (advanced) -----------------------------------------------
  {
    id: "tenant-analytics",
    label: "Tenant Analytics",
    href: "/settings/tenant-analytics",
    icon: BarChart3,
    advanced: true,
    group: "Analytics",
  },
  {
    id: "activity-feed",
    label: "Activity Feed",
    href: "/settings/activity-feed",
    icon: ActivitySquare,
    advanced: true,
    group: "Analytics",
  },

  // --- Localization (advanced) ---------------------------------------------
  {
    id: "localization",
    label: "Localization",
    href: "/settings/localization",
    icon: Globe,
    advanced: true,
    group: "Localization",
  },

  // --- Super Admin (advanced) ----------------------------------------------
  {
    id: "super-admin",
    label: "Super Admin Overview",
    href: "/settings/super-admin",
    icon: Building2,
    advanced: true,
    group: "Super Admin",
  },
  {
    id: "super-admin-admins",
    label: "Super Admins",
    href: "/settings/super-admin/admins",
    icon: UserCog,
    advanced: true,
    group: "Super Admin",
  },
  {
    id: "super-admin-health",
    label: "Platform Health",
    href: "/settings/super-admin/health",
    icon: Activity,
    advanced: true,
    group: "Super Admin",
  },
  {
    id: "super-admin-tenants",
    label: "Tenants",
    href: "/settings/super-admin/tenants",
    icon: Building2,
    advanced: true,
    group: "Super Admin",
  },

  // --- Workflows (Legacy Views) (advanced) ---------------------------------
  {
    id: "workflows",
    label: "Workflows Overview",
    href: "/settings/workflows",
    icon: GitFork,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-templates",
    label: "Templates",
    href: "/settings/workflows/templates",
    icon: GitFork,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-routing",
    label: "Dynamic Routing",
    href: "/settings/workflows/routing",
    icon: Zap,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-email",
    label: "Email Approvals",
    href: "/settings/workflows/email",
    icon: Mail,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-simulation",
    label: "Simulator",
    href: "/settings/workflows/simulation",
    icon: Activity,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-approvals",
    label: "Approvals",
    href: "/settings/workflows/approvals",
    icon: CheckSquare,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-bulk",
    label: "Bulk Approvals",
    href: "/settings/workflows/bulk",
    icon: CheckSquare,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-escalations",
    label: "Escalation Logs",
    href: "/settings/workflows/escalations",
    icon: ShieldAlert,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-analytics",
    label: "Workflow Analytics",
    href: "/settings/workflows/analytics",
    icon: BarChart3,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },
  {
    id: "workflows-advanced",
    label: "Advanced Rules",
    href: "/settings/workflows/advanced",
    icon: Workflow,
    advanced: true,
    group: "Workflows (Legacy Views)",
  },

  // --- Import / Export Details (advanced) ----------------------------------
  {
    id: "import",
    label: "Import Data",
    href: "/settings/import",
    icon: Upload,
    advanced: true,
    group: "Import / Export Details",
  },
  {
    id: "export",
    label: "Export Data",
    href: "/settings/export",
    icon: Download,
    advanced: true,
    group: "Import / Export Details",
  },
];
