"use client";

import {
  ShoppingCart,
  FileText,
  Building,
  ClipboardList,
  Truck,
  BarChart3,
  Settings,
  ArrowLeftRight,
  ShieldCheck,
  BadgeCent,
  AlertTriangle,
  Gavel,
  Calendar,
  Star,
  CheckSquare,
} from "lucide-react";
import type { ModuleTab } from "@unerp/ui-layout";

export {
  ModuleTabLayout as ProcurementTabLayout,
  type ModuleTab as ProcurementTab,
  type ModuleTabLayoutProps as ProcurementTabLayoutProps,
  SubTabBar,
  type SubTab,
} from "@unerp/ui-layout";

export const PROCUREMENT_TABS: ModuleTab[] = [
  {
    id: "overview",
    label: "Dashboard",
    href: "/procurement",
    icon: ShoppingCart,
    description: "Procurement overview, spend KPIs, and active orders",
  },
  {
    id: "requisitions",
    label: "Requisitions",
    href: "/procurement/requisitions",
    icon: ClipboardList,
    description: "Purchase requisitions",
  },
  {
    id: "purchase-orders",
    label: "Purchase Orders",
    href: "/procurement/purchase-orders",
    icon: FileText,
    description: "Purchase orders and approvals",
  },
  {
    id: "purchase-receipts",
    label: "Receipts & Matching",
    href: "/procurement/purchase-receipts",
    icon: Truck,
    description: "Goods receipts and 3-way matching",
  },
  {
    id: "vendors-rfqs",
    label: "Vendors & RFQs",
    href: "/procurement/rfqs",
    icon: Building,
    description: "Vendors, RFQs, and supplier quotations",
  },
  {
    id: "returns",
    label: "Returns",
    href: "/procurement/returns",
    icon: ArrowLeftRight,
    description: "Purchase returns and debit notes",
  },
  {
    id: "blanket-agreements",
    label: "Blanket Agreements",
    href: "/procurement/blanket-agreements",
    icon: FileText,
    advanced: true,
    group: "Procurement",
    description: "Blanket purchase agreements and release orders",
  },
  {
    id: "subcontracting",
    label: "Subcontracting",
    href: "/procurement/subcontracting",
    icon: ShieldCheck,
    advanced: true,
    group: "Procurement",
    description: "Subcontracting order management",
  },
  {
    id: "debit-notes",
    label: "Debit Notes",
    href: "/procurement/debit-notes",
    icon: BadgeCent,
    advanced: true,
    group: "Procurement",
    description: "Debit note lifecycle management",
  },
  {
    id: "vendor-rma",
    label: "Vendor RMA",
    href: "/procurement/vendor-rma",
    icon: Truck,
    advanced: true,
    group: "Supplier Quality",
    description: "Return merchandise authorization requests",
  },
  {
    id: "ncr-car",
    label: "NCR & CAR",
    href: "/procurement/ncr-car",
    icon: AlertTriangle,
    advanced: true,
    group: "Supplier Quality",
    description: "Non-conformance reports and corrective actions",
  },
  {
    id: "payment-schedules",
    label: "Payment Schedules",
    href: "/procurement/payment-schedules",
    icon: Calendar,
    advanced: true,
    group: "Finance",
    description: "Payment schedule tracking",
  },
  {
    id: "supplier-scorecards",
    label: "Scorecards",
    href: "/procurement/supplier-scorecards",
    icon: Star,
    advanced: true,
    group: "Analytics",
    description: "Supplier performance scorecards",
  },
  {
    id: "auctions",
    label: "RFQ Auctions",
    href: "/procurement/rfq-auctions",
    icon: Gavel,
    advanced: true,
    group: "Analytics",
    description: "Reverse auction management",
  },
  {
    id: "analytics",
    label: "Analytics",
    href: "/procurement/analytics",
    icon: BarChart3,
    advanced: true,
    group: "Analytics",
    description: "Procurement spend analytics",
  },
  {
    id: "approvals",
    label: "Approvals",
    href: "/procurement/approvals",
    icon: CheckSquare,
    advanced: true,
    group: "Procurement",
    description: "Approval workflow management",
  },
  {
    id: "portal",
    label: "Vendor Portal",
    href: "/procurement/portal",
    icon: Building,
    advanced: true,
    group: "Procurement",
    description: "Vendor portal management",
  },
  {
    id: "settings",
    label: "Settings",
    href: "/procurement/settings",
    icon: Settings,
    advanced: true,
    group: "Procurement",
    description: "Procurement module settings",
  },
];
